AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      TracingEnabled: true
      OpenApiVersion: 3.0.2
  all:
    Type: AWS::Serverless::Function
    Properties:
      Handler: il.co.nocancer.functions.Entrypoint::handleRequest
      CodeUri: s3://lambda-artifacts-anticancerserver/d8d79710dd1fbf2cff500505729238e1
      Runtime: java11
      Description: Java function
      MemorySize: 512
      Timeout: 35
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      Layers:
      - Ref: libs
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId:
              Ref: api
            Path: /{proxy+}
            Method: ANY
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: anticancerserver-lib
      Description: Dependencies for the blank-java sample app.
      ContentUri: s3://lambda-artifacts-anticancerserver/49632588a978b03f2d7109b5406c0c88
      CompatibleRuntimes:
      - java11
