AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      TracingEnabled: true
      OpenApiVersion: 3.0.2
  all:
    Type: AWS::Serverless::Function
    Properties:
      Handler: il.co.nocancer.functions.Entrypoint::handleRequest
      CodeUri: ${lambda_code}
      Runtime: java11
      Description: Java function
      MemorySize: 512
      Timeout: 35
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      Layers:
        - !Ref libs
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref api
            Path: /{proxy+}
            Method: ANY
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ${project_name}-lib
      Description: Dependencies for the blank-java sample app.
      ContentUri: ${library_code}
      CompatibleRuntimes:
        - java11
