export const AnotherQuiltLog = `---- Crashed! ----
Date/Time: 2023/05/15 14:26:24.9759

-- Crash --

org.quiltmc.loader.impl.FormattedException: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_437 failed
\tat org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:529)
\tat org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
\tat org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
\tat org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
\tat org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
\tat org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_437 failed
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:456)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:246)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:164)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228)
\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
\tat net.minecraft.class_6396.handler$dic000$iris$fillSystemDetails(class_6396.java:525)
\tat net.minecraft.class_6396.<init>(class_6396.java:58)
\tat net.minecraft.class_128.<init>(class_128.java:34)
\tat net.minecraft.class_128.method_24305(class_128.java:274)
\tat net.minecraft.client.main.Main.main(Main.java:152)
\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)
\tat org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
\t... 5 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
\tat org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
\tat org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
\tat org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:451)
\t... 20 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#lodestone:lodestone.mixins.json:ScreenMixin from mod lodestone] from phase [DEFAULT] in config [#lodestone:lodestone.mixins.json] FAILED during APPLY
\tat org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
\tat org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
\tat org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
\t... 23 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on lodestone$beforeBackgroundParticle could not find any targets matching 'Lnet/minecraft/class_437;method_25433(Lnet/minecraft/class_4587;I)V' in net.minecraft.class_437. Using refmap lodestone-refmap.json [PREINJECT Applicator Phase -> #lodestone:lodestone.mixins.json:ScreenMixin from mod lodestone -> Prepare Injections ->  -> handler$fen000$lodestone$beforeBackgroundParticle(Lnet/minecraft/class_4587;ILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
\tat org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656)
\tat org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587)
\tat org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330)
\tat org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316)
\tat org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308)
\tat org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
\tat jdk.internal.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source)
\tat java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
\tat java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
\tat java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
\tat org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149)
\tat org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708)
\tat org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330)
\tat org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
\tat org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
\tat org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
\tat org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
\tat org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
\tat org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
\t... 23 more


-- Mods --

| Index | Mod                                                                   | ID                                                    | Version                     | Plugin                 | File(s)                                                                                                   | Sub-Files                                                                           | Sub-Files                            |
|------:|-----------------------------------------------------------------------|-------------------------------------------------------|-----------------------------|------------------------|-----------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|--------------------------------------|
|    76 | Animatica                                                             | animatica                                             | 0.5+1.19                    | quilted_fabric_loader  | <mods>\\animatica-0.5+1.19.jar                                                                             |                                                                                     |                                      |
|    40 | Better Beds                                                           | betterbeds                                            | 1.2.0                       | quilted_fabric_loader  | <mods>\\betterbeds-1.2.0.jar                                                                               |                                                                                     |                                      |
|     0 | Better FPS distance Mod                                               | betterfpsdist                                         | 1.19.4-2.5                  | quilted_fabric_loader  | <mods>\\betterfpsdist-fabric-1.19.4-2.5.jar                                                                |                                                                                     |                                      |
|   196 | BetterF3                                                              | betterf3                                              | 6.0.1                       | quilted_fabric_loader  | <mods>\\BetterF3-6.0.1-Fabric-1.19.4.jar                                                                   |                                                                                     |                                      |
|   195 | Bobby                                                                 | bobby                                                 | 4.0.5                       | quilted_fabric_loader  | <mods>\\bobby-4.0.5.jar                                                                                    |                                                                                     |                                      |
|    39 | CIT Resewn                                                            | citresewn                                             | 1.1.3+1.19.4                | quilted_fabric_loader  | <mods>\\CITResewn-1.1.3+1.19.4.jar                                                                         |                                                                                     |                                      |
|     9 | CIT Resewn: Defaults                                                  | citresewn-defaults                                    | 1.1.3+1.19.4                | quilted_fabric_loader  | <mods>\\CITResewn-1.1.3+1.19.4.jar                                                                         | /META-INF/jars/citresewn-defaults-1.1.3+1.19.4.jar                                  |                                      |
|     6 | CaffeineConfig                                                        | caffeineconfig                                        | 1.1.0+1.17                  | quilted_fabric_loader  | <mods>\\sodium-extra-0.4.18+mc1.19.4-build.100.jar                                                         | /META-INF/jars/CaffeineConfig-1.1.0+1.17.jar                                        |                                      |
|    93 | Capes                                                                 | capes                                                 | 1.5.2+1.19.3                | quilted_fabric_loader  | <mods>\\capes-1.5.2+1.19.3-fabric.jar                                                                      |                                                                                     |                                      |
|   180 | Carpet Mod                                                            | carpet                                                | 1.4.101+v230319             | quilted_fabric_loader  | <mods>\\fabric-carpet-1.19.4-1.4.101+v230319.jar                                                           |                                                                                     |                                      |
|   126 | Charmonium                                                            | charmonium                                            | 4.2.1                       | quilted_fabric_loader  | <mods>\\charmonium-fabric-1.19.2-4.2.1.jar                                                                 |                                                                                     |                                      |
|   186 | Cloth Config v10                                                      | cloth-config                                          | 10.0.96                     | quilted_fabric_loader  | <mods>\\cloth-config-10.0.96-fabric.jar                                                                    |                                                                                     |                                      |
|    50 | CompleteConfig                                                        | completeconfig                                        | 2.3.1                       | quilted_fabric_loader  | <mods>\\completeconfig-2.3.1.jar                                                                           |                                                                                     |                                      |
|   109 | Concurrent Chunk Management Engine                                    | c2me                                                  | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         |                                                                                     |                                      |
|    80 | Concurrent Chunk Management Engine (Base)                             | c2me-base                                             | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-base-mc1.19.4-0.2.0+alpha.10.51.jar                             |                                      |
|    38 | Concurrent Chunk Management Engine (Client/Uncap View Distance)       | c2me-client-uncapvd                                   | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-client-uncapvd-mc1.19.4-0.2.0+alpha.10.51.jar                   |                                      |
|    53 | Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues)  | c2me-fixes-chunkio-threading-issues                   | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-fixes-chunkio-threading-issues-mc1.19.4-0.2.0+alpha.10.51.jar   |                                      |
|    18 | Concurrent Chunk Management Engine (Fixes/General/Threading Issues)   | c2me-fixes-general-threading-issues                   | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-fixes-general-threading-issues-mc1.19.4-0.2.0+alpha.10.51.jar   |                                      |
|    74 | Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues)  | c2me-fixes-worldgen-threading-issues                  | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-fixes-worldgen-threading-issues-mc1.19.4-0.2.0+alpha.10.51.jar  |                                      |
|    75 | Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs)      | c2me-fixes-worldgen-vanilla-bugs                      | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-fixes-worldgen-vanilla-bugs-mc1.19.4-0.2.0+alpha.10.51.jar      |                                      |
|    73 | Concurrent Chunk Management Engine (No Tick View Distance)            | c2me-notickvd                                         | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-notickvd-mc1.19.4-0.2.0+alpha.10.51.jar                         |                                      |
|    22 | Concurrent Chunk Management Engine (Optimizations/Chunk Access)       | c2me-opts-chunk-access                                | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-opts-chunk-access-mc1.19.4-0.2.0+alpha.10.51.jar                |                                      |
|    54 | Concurrent Chunk Management Engine (Optimizations/Chunk IO)           | c2me-opts-chunkio                                     | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-opts-chunkio-mc1.19.4-0.2.0+alpha.10.51.jar                     |                                      |
|     8 | Concurrent Chunk Management Engine (Optimizations/General WorldGen)   | c2me-opts-worldgen-general                            | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-opts-worldgen-general-mc1.19.4-0.2.0+alpha.10.51.jar            |                                      |
|    27 | Concurrent Chunk Management Engine (Optimizations/Math)               | c2me-opts-math                                        | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-opts-math-mc1.19.4-0.2.0+alpha.10.51.jar                        |                                      |
|    82 | Concurrent Chunk Management Engine (Optimizations/Memory Allocations) | c2me-opts-allocs                                      | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-opts-allocs-mc1.19.4-0.2.0+alpha.10.51.jar                      |                                      |
|    51 | Concurrent Chunk Management Engine (Optimizations/Scheduling)         | c2me-opts-scheduling                                  | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-opts-scheduling-mc1.19.4-0.2.0+alpha.10.51.jar                  |                                      |
|    62 | Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen)   | c2me-opts-worldgen-vanilla                            | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-opts-worldgen-vanilla-mc1.19.4-0.2.0+alpha.10.51.jar            |                                      |
|    26 | Concurrent Chunk Management Engine (Rewrites/Chunk IO)                | c2me-rewrites-chunkio                                 | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-rewrites-chunkio-mc1.19.4-0.2.0+alpha.10.51.jar                 |                                      |
|    77 | Concurrent Chunk Management Engine (Server Utils)                     | c2me-server-utils                                     | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-server-utils-mc1.19.4-0.2.0+alpha.10.51.jar                     |                                      |
|     4 | Concurrent Chunk Management Engine (Threading/Lighting)               | c2me-threading-lighting                               | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-threading-lighting-mc1.19.4-0.2.0+alpha.10.51.jar               |                                      |
|    25 | Concurrent Chunk Management Engine (Threading/WorldGen)               | c2me-threading-worldgen                               | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-threading-worldgen-mc1.19.4-0.2.0+alpha.10.51.jar               |                                      |
|    70 | Concurrent Chunk Management Engine (Threading/WorldGen)               | c2me-threading-chunkio                                | 0.2.0+alpha.10.51           | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/c2me-threading-chunkio-mc1.19.4-0.2.0+alpha.10.51.jar                |                                      |
|    68 | Continuity                                                            | continuity                                            | 3.0.0-beta.2+1.19.3         | quilted_fabric_loader  | <mods>\\continuity-3.0.0-beta.2+1.19.3.jar                                                                 |                                                                                     |                                      |
|    81 | CrowdinTranslate                                                      | crowdin-translate                                     | 1.4+1.19.3                  | quilted_fabric_loader  | <mods>\\sodium-extra-0.4.18+mc1.19.4-build.100.jar                                                         | /META-INF/jars/crowdin-translate-1.4+1.19.3.jar                                     |                                      |
|     3 | Cull Leaves                                                           | cullleaves                                            | 3.0.3                       | quilted_fabric_loader  | <mods>\\cullleaves-fabric-3.0.3.jar                                                                        |                                                                                     |                                      |
|   146 | Custom Entity Models                                                  | cem                                                   | 0.7.3                       | quilted_fabric_loader  | <mods>\\cem-0.7.3.jar                                                                                      |                                                                                     |                                      |
|   150 | Debugify                                                              | debugify                                              | 1.19.4+2.2                  | quilted_fabric_loader  | <mods>\\Debugify-1.19.4+2.2.jar                                                                            |                                                                                     |                                      |
|     7 | Dynamic FPS                                                           | dynamicfps                                            | 2.2.0                       | quilted_fabric_loader  | <mods>\\dynamic-fps-2.2.0.jar                                                                              |                                                                                     |                                      |
|   190 | Effective                                                             | effective                                             | 1.6+1.19.2                  | quilt_loader           | <mods>\\effective-1.6+1.19.2.jar                                                                           |                                                                                     |                                      |
|    15 | Enhanced Block Entities                                               | enhancedblockentities                                 | 0.8+1.19.3                  | quilted_fabric_loader  | <mods>\\enhancedblockentities-0.8+1.19.3.jar                                                               |                                                                                     |                                      |
|   162 | Entity Collision FPS Fix                                              | entitycollisionfpsfix                                 | **.**.**.**                     | quilted_fabric_loader  | <mods>\\Entity_Collision_FPS_Fix-fabric-1.19-2.0.0.0.jar                                                   |                                                                                     |                                      |
|   116 | Entity Texture Features                                               | entity_texture_features                               | 4.4.4                       | quilted_fabric_loader  | <mods>\\entity_texture_features_fabric_1.19.4-4.4.4.jar                                                    |                                                                                     |                                      |
|    13 | EntityCulling-Fabric                                                  | entityculling                                         | 1.6.2-mc1.19.4              | quilted_fabric_loader  | <mods>\\entityculling-fabric-1.6.2-mc1.19.4.jar                                                            |                                                                                     |                                      |
|   121 | Fabric Language Kotlin                                                | fabric-language-kotlin                                | 1.9.4+kotlin.1.8.21         | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                     |                                                                                     |                                      |
|   135 | FabricSkyBoxes                                                        | fabricskyboxes                                        | 0.6.5+mc1.19.4              | quilted_fabric_loader  | <mods>\\fabricskyboxes-0.6.5+mc1.19.4.jar                                                                  |                                                                                     |                                      |
|   119 | Falling Leaves                                                        | fallingleaves                                         | 1.15.0+1.19.4               | quilted_fabric_loader  | <mods>\\fallingleaves-1.15.0+1.19.4.jar                                                                    |                                                                                     |                                      |
|   164 | FerriteCore                                                           | ferritecore                                           | 5.2.0                       | quilted_fabric_loader  | <mods>\\ferritecore-5.2.0-fabric.jar                                                                       |                                                                                     |                                      |
|    43 | GBfabrictools                                                         | gbfabrictools                                         | 1.3.4+1.19                  | quilted_fabric_loader  | <mods>\\durabilityviewer-1.19.1-fabric0.58.5-1.10.3.jar                                                    | /META-INF/jars/GBfabrictools-1.3.4+1.19.jar                                         |                                      |
|    47 | Giselbaers Durability Viewer                                          | durabilityviewer                                      | 1.19.1-fabric0.58.5-1.10.3  | quilted_fabric_loader  | <mods>\\durabilityviewer-1.19.1-fabric0.58.5-1.10.3.jar                                                    |                                                                                     |                                      |
|    57 | Illuminations                                                         | illuminations                                         | 1.10.11                     | quilted_fabric_loader  | <mods>\\illuminations-1.10.11.jar                                                                          |                                                                                     |                                      |
|   205 | ImmediatelyFast                                                       | immediatelyfast                                       | 1.1.12                      | quilted_fabric_loader  | <mods>\\ImmediatelyFast-1.1.12+1.19.4.jar                                                                  |                                                                                     |                                      |
|    20 | Indium                                                                | indium                                                | 1.0.15+mc1.19.4             | quilted_fabric_loader  | <mods>\\indium-1.0.15+mc1.19.4.jar                                                                         |                                                                                     |                                      |
|   151 | Iris                                                                  | iris                                                  | 1.6.3                       | quilted_fabric_loader  | <mods>\\iris-mc1.19.4-1.6.3.jar                                                                            |                                                                                     |                                      |
|    32 | Item Scroller                                                         | itemscroller                                          | 0.19.2                      | quilted_fabric_loader  | <mods>\\itemscroller-fabric-1.19.4-0.19.2.jar                                                              |                                                                                     |                                      |
|   104 | Kirin UI                                                              | kirin                                                 | 1.14.0                      | quilted_fabric_loader  | <mods>\\PresenceFootsteps-1.8.0.jar                                                                        | /META-INF/jars/kirin-1.14.0.jar                                                     |                                      |
|    60 | Krypton                                                               | krypton                                               | 0.2.2                       | quilted_fabric_loader  | <mods>\\krypton-0.2.2.jar                                                                                  |                                                                                     |                                      |
|   113 | LambDynamicLights                                                     | lambdynlights                                         | 2.3.0+1.19.4                | quilted_fabric_loader  | <mods>\\lambdynamiclights-2.3.0+1.19.4.jar                                                                 |                                                                                     |                                      |
|   176 | LambdaBetterGrass                                                     | lambdabettergrass                                     | 1.5.0+1.19.4                | quilt_loader           | <mods>\\lambdabettergrass-1.5.0+1.19.4.jar                                                                 |                                                                                     |                                      |
|    67 | LazyDFU                                                               | lazydfu                                               | 0.1.3                       | quilted_fabric_loader  | <mods>\\lazydfu-0.1.3.jar                                                                                  |                                                                                     |                                      |
|   147 | LibZoomer                                                             | libzoomer                                             | 0.6.0+1.19.4                | quilt_loader           | <mods>\\ok_zoomer-5.0.0-beta.11+1.19.4.jar                                                                 | /META-INF/jars/LibZoomer-0.6.0+1.19.4.jar                                           |                                      |
|    16 | Litematica                                                            | litematica                                            | 0.14.3                      | quilted_fabric_loader  | <mods>\\litematica-fabric-1.19.4-0.14.3.jar                                                                |                                                                                     |                                      |
|   124 | Lithium                                                               | lithium                                               | 0.11.1                      | quilted_fabric_loader  | <mods>\\lithium-fabric-mc1.19.4-0.11.1.jar                                                                 |                                                                                     |                                      |
|   206 | LodestoneLib                                                          | lodestone                                             | 413d9b4712                  | quilt_loader           | <mods>\\effective-1.6+1.19.2.jar                                                                           | /META-INF/jars/LodestoneLib-Quilt-413d9b4712.jar                                    |                                      |
|    12 | MaLiLib                                                               | malilib                                               | 0.15.4                      | quilted_fabric_loader  | <mods>\\malilib-fabric-1.19.4-0.15.4.jar                                                                   |                                                                                     |                                      |
|   193 | Memory Leak Fix                                                       | memoryleakfix                                         | 1.0.0                       | quilted_fabric_loader  | <mods>\\memoryleakfix-fabric-1.17+-1.0.0.jar                                                               |                                                                                     |                                      |
|    42 | MidnightLib                                                           | midnightlib                                           | 1.1.0                       | quilted_fabric_loader  | <mods>\\cullleaves-fabric-3.0.3.jar                                                                        | /META-INF/jars/midnightlib-1.1.0-fabric.jar                                         |                                      |
|   197 | Minecraft                                                             | minecraft                                             | 1.19.4                      | quilt_loader           | <game>\\.quilt\\remappedJars\\minecraft-1.19.4-0.18.10\\client-intermediary.jar                               |                                                                                     |                                      |
|    41 | MiniHUD                                                               | minihud                                               | 0.26.2                      | quilted_fabric_loader  | <mods>\\minihud-fabric-1.19.4-0.26.2.jar                                                                   |                                                                                     |                                      |
|   110 | MixinExtras                                                           | com_github_llamalad7_mixinextras                      | 0.2.0-beta.6                | quilted_fabric_loader  | <mods>\\memoryleakfix-fabric-1.17+-1.0.0.jar                                                               | /META-INF/jars/mixinextras-fabric-0.2.0-beta.6.jar                                  |                                      |
|   167 | Mod Menu                                                              | modmenu                                               | 6.2.2                       | quilted_fabric_loader  | <mods>\\modmenu-6.2.2.jar                                                                                  |                                                                                     |                                      |
|   207 | More Culling                                                          | moreculling                                           | 1.19.4-0.17.0               | quilted_fabric_loader  | <mods>\\moreculling-1.19.4-0.17.0.jar                                                                      |                                                                                     |                                      |
|   130 | No Chat Reports                                                       | nochatreports                                         | 1.19.4-v2.1.1               | quilted_fabric_loader  | <mods>\\NoChatReports-FABRIC-1.19.4-v2.1.1.jar                                                             |                                                                                     |                                      |
|    24 | No Fade                                                               | nofade                                                | 1.18-2.0.1                  | quilted_fabric_loader  | <mods>\\nofade-1.18-2.0.1.jar                                                                              |                                                                                     |                                      |
|   125 | Ok Zoomer                                                             | ok_zoomer                                             | 5.0.0-beta.11+1.19.4        | quilt_loader           | <mods>\\ok_zoomer-5.0.0-beta.11+1.19.4.jar                                                                 |                                                                                     |                                      |
|   213 | OpenJDK 64-Bit Server VM                                              | java                                                  | 17                          | quilt_loader           | C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.3.7-hotspot                                                    |                                                                                     |                                      |
|   118 | Physics Mod                                                           | physicsmod                                            | 2.12.3                      | quilted_fabric_loader  | <mods>\\physics-mod-2.12.3-mc-1.19.4-fabric.jar                                                            |                                                                                     |                                      |
|   182 | Presence Footsteps                                                    | presencefootsteps                                     | 1.8.0                       | quilted_fabric_loader  | <mods>\\PresenceFootsteps-1.8.0.jar                                                                        |                                                                                     |                                      |
|   142 | Pride Lib                                                             | pride                                                 | 1.2.0+1.19.4                | quilted_fabric_loader  | <mods>\\lambdynamiclights-2.3.0+1.19.4.jar                                                                 | /META-INF/jars/pridelib-1.2.0+1.19.4.jar                                            |                                      |
|   144 | Quilt Advancement API                                                 | quilt_advancement                                     | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/advancement-5.0.0-beta.5+1.19.4.jar                                  |                                      |
|   100 | Quilt Base API                                                        | quilt_base                                            | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/qsl_base-5.0.0-beta.5+1.19.4.jar                                     |                                      |
|   139 | Quilt Biome API                                                       | quilt_biome                                           | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/biome-5.0.0-beta.5+1.19.4.jar                                        |                                      |
|   165 | Quilt Block Content Registry API                                      | quilt_block_content_registry                          | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/block_content_registry-5.0.0-beta.5+1.19.4.jar                       |                                      |
|    92 | Quilt Block Entity API                                                | quilt_block_entity                                    | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/block_entity-5.0.0-beta.5+1.19.4.jar                                 |                                      |
|   101 | Quilt Block Extensions API                                            | quilt_block_extensions                                | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/block_extensions-5.0.0-beta.5+1.19.4.jar                             |                                      |
|   212 | Quilt Chat API                                                        | quilt_chat                                            | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/chat-5.0.0-beta.5+1.19.4.jar                                         |                                      |
|   194 | Quilt Client Command API                                              | quilt_client_command                                  | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/client_command-5.0.0-beta.5+1.19.4.jar                               |                                      |
|   177 | Quilt Command API                                                     | quilt_command                                         | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/command-5.0.0-beta.5+1.19.4.jar                                      |                                      |
|   171 | Quilt Crash Info                                                      | quilt_crash_info                                      | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/crash_info-5.0.0-beta.5+1.19.4.jar                                   |                                      |
|   181 | Quilt Dimension API                                                   | quilt_dimension                                       | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/dimension-5.0.0-beta.5+1.19.4.jar                                    |                                      |
|   136 | Quilt Entity API                                                      | quilt_entity                                          | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/entity-5.0.0-beta.5+1.19.4.jar                                       |                                      |
|    83 | Quilt Entity Events                                                   | quilt_entity_events                                   | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/entity_events-5.0.0-beta.5+1.19.4.jar                                |                                      |
|   166 | Quilt Entity Networking API                                           | quilt_entity_networking                               | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/entity_networking-5.0.0-beta.5+1.19.4.jar                            |                                      |
|    98 | Quilt Entity Rendering API                                            | quilt_entity_rendering                                | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/entity_rendering-5.0.0-beta.5+1.19.4.jar                             |                                      |
|   140 | Quilt Item Content Registry API                                       | quilt_item_content_registry                           | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/item_content_registry-5.0.0-beta.5+1.19.4.jar                        |                                      |
|   208 | Quilt Item Extensions API                                             | quilt_item_extensions                                 | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/item_extensions-5.0.0-beta.5+1.19.4.jar                              |                                      |
|   127 | Quilt Item Setting API                                                | quilt_item_setting                                    | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/item_setting-5.0.0-beta.5+1.19.4.jar                                 |                                      |
|   178 | Quilt Lifecycle Events                                                | quilt_lifecycle_events                                | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/lifecycle_events-5.0.0-beta.5+1.19.4.jar                             |                                      |
|   157 | Quilt Loader                                                          | quilt_loader                                          | 0.18.10                     | quilt_loader           | <user>\\AppData\\Roaming\\PrismLauncher\\libraries\\org\\quiltmc\\quilt-loader\\0.18.10\\quilt-loader-0.18.10.jar  |                                                                                     |                                      |
|   158 | Quilt Multipart Entity API                                            | quilt_entity_multipart                                | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/multipart-5.0.0-beta.5+1.19.4.jar                                    |                                      |
|   198 | Quilt Networking                                                      | quilt_networking                                      | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/networking-5.0.0-beta.5+1.19.4.jar                                   |                                      |
|   174 | Quilt Point of Interest API                                           | quilt_point_of_interest                               | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/point_of_interest-5.0.0-beta.5+1.19.4.jar                            |                                      |
|   129 | Quilt Recipe API                                                      | quilt_recipe                                          | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/recipe-5.0.0-beta.5+1.19.4.jar                                       |                                      |
|    94 | Quilt Registry API                                                    | quilt_registry                                        | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/registry-5.0.0-beta.5+1.19.4.jar                                     |                                      |
|   168 | Quilt Registry Entry Attachment                                       | quilt_registry_entry_attachment                       | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/registry_entry_attachment-5.0.0-beta.5+1.19.4.jar                    |                                      |
|    86 | Quilt Resource Loader                                                 | quilt_resource_loader                                 | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/resource_loader-5.0.0-beta.5+1.19.4.jar                              |                                      |
|   170 | Quilt Screen API                                                      | quilt_screen                                          | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/screen-5.0.0-beta.5+1.19.4.jar                                       |                                      |
|   192 | Quilt Status Effect API                                               | quilt_status_effect                                   | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/status_effect-5.0.0-beta.5+1.19.4.jar                                |                                      |
|    90 | Quilt Surface Rule API                                                | quilt_surface_rule                                    | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/surface_rule-5.0.0-beta.5+1.19.4.jar                                 |                                      |
|   138 | Quilt Tags API                                                        | quilt_tags                                            | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/tags-5.0.0-beta.5+1.19.4.jar                                         |                                      |
|   131 | Quilt Testing API                                                     | quilt_testing                                         | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/testing-5.0.0-beta.5+1.19.4.jar                                      |                                      |
|   163 | Quilt Tooltip API                                                     | quilt_tooltip                                         | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/tooltip-5.0.0-beta.5+1.19.4.jar                                      |                                      |
|    99 | Quilt Vehicle API                                                     | quilt_vehicle                                         | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/vehicle-5.0.0-beta.5+1.19.4.jar                                      |                                      |
|    88 | Quilt Villager API                                                    | quilt_villager                                        | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/villager-5.0.0-beta.5+1.19.4.jar                                     |                                      |
|    95 | Quilted Fabric API                                                    | quilted_fabric_api                                    | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      |                                                                                     |                                      |
|    91 | Quilted Fabric API Base                                               | quilted_fabric_api_base                               | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-api-base-6.0.0-beta.6+0.79.0-1.19.4.jar                       |                                      |
|   128 | Quilted Fabric API Lookup API (v1)                                    | quilted_fabric_api_lookup_api_v1                      | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-api-lookup-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar              |                                      |
|   179 | Quilted Fabric Biome API (v1)                                         | quilted_fabric_biome_api_v1                           | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-biome-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                   |                                      |
|   209 | Quilted Fabric Block API (v1)                                         | quilted_fabric_block_api_v1                           | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-block-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                   |                                      |
|   200 | Quilted Fabric BlockRenderLayer Registration (v1)                     | quilted_fabric_blockrenderlayer_v1                    | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-blockrenderlayer-v1-6.0.0-beta.6+0.79.0-1.19.4.jar            |                                      |
|   102 | Quilted Fabric Client Tags                                            | quilted_fabric_client_tags_api_v1                     | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-client-tags-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar             |                                      |
|   122 | Quilted Fabric Command API (v1)                                       | quilted_fabric_command_api_v1                         | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-command-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                 |                                      |
|   172 | Quilted Fabric Command API (v2)                                       | quilted_fabric_command_api_v2                         | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-command-api-v2-6.0.0-beta.6+0.79.0-1.19.4.jar                 |                                      |
|   155 | Quilted Fabric Commands (v0)                                          | quilted_fabric_commands_v0                            | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-commands-v0-6.0.0-beta.6+0.79.0-1.19.4.jar                    |                                      |
|   159 | Quilted Fabric Containers (v0)                                        | quilted_fabric_containers_v0                          | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-containers-v0-6.0.0-beta.6+0.79.0-1.19.4.jar                  |                                      |
|   154 | Quilted Fabric Content Registries (v0)                                | quilted_fabric_content_registries_v0                  | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-content-registries-v0-6.0.0-beta.6+0.79.0-1.19.4.jar          |                                      |
|   105 | Quilted Fabric Convention Tags API (v1)                               | quilted_fabric_convention_tags_api_v1                 | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-convention-tags-v1-6.0.0-beta.6+0.79.0-1.19.4.jar             |                                      |
|   199 | Quilted Fabric Crash Report Info (v1)                                 | quilted_fabric_crash_report_info_v1                   | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-crash-report-info-v1-6.0.0-beta.6+0.79.0-1.19.4.jar           |                                      |
|   153 | Quilted Fabric Data Generation API (v1)                               | quilted_fabric_data_generation_api_v1                 | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-data-generation-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar         |                                      |
|   134 | Quilted Fabric Dimensions API (v1)                                    | quilted_fabric_dimensions_v1                          | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-dimensions-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                  |                                      |
|   173 | Quilted Fabric Entity Events (v1)                                     | quilted_fabric_entity_events_v1                       | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-entity-events-v1-6.0.0-beta.6+0.79.0-1.19.4.jar               |                                      |
|   149 | Quilted Fabric Events Interaction (v0)                                | quilted_fabric_events_interaction_v0                  | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-events-interaction-v0-6.0.0-beta.6+0.79.0-1.19.4.jar          |                                      |
|   161 | Quilted Fabric Events Lifecycle (v0)                                  | quilted_fabric_events_lifecycle_v0                    | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-events-lifecycle-v0-6.0.0-beta.6+0.79.0-1.19.4.jar            |                                      |
|   211 | Quilted Fabric Game Rule API (v1)                                     | quilted_fabric_game_rule_api_v1                       | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-game-rule-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar               |                                      |
|    97 | Quilted Fabric Item API (v1)                                          | quilted_fabric_item_api_v1                            | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-item-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                    |                                      |
|    96 | Quilted Fabric Item Group API (v1)                                    | quilted_fabric_item_group_api_v1                      | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-item-group-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar              |                                      |
|   201 | Quilted Fabric Key Binding API (v1)                                   | quilted_fabric_key_binding_api_v1                     | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-key-binding-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar             |                                      |
|   204 | Quilted Fabric Key Bindings (v0)                                      | quilted_fabric_keybindings_v0                         | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-keybindings-v0-6.0.0-beta.6+0.79.0-1.19.4.jar                 |                                      |
|   112 | Quilted Fabric Lifecycle Events (v1)                                  | quilted_fabric_lifecycle_events_v1                    | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-lifecycle-events-v1-6.0.0-beta.6+0.79.0-1.19.4.jar            |                                      |
|   114 | Quilted Fabric Loot API (v2)                                          | quilted_fabric_loot_api_v2                            | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-loot-api-v2-6.0.0-beta.6+0.79.0-1.19.4.jar                    |                                      |
|   203 | Quilted Fabric Loot Tables (v1)                                       | quilted_fabric_loot_tables_v1                         | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-loot-tables-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                 |                                      |
|   202 | Quilted Fabric Message API (v1)                                       | quilted_fabric_message_api_v1                         | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-message-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                 |                                      |
|   184 | Quilted Fabric Mining Level API (v1)                                  | quilted_fabric_mining_level_api_v1                    | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-mining-level-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar            |                                      |
|   111 | Quilted Fabric Models (v0)                                            | quilted_fabric_models_v0                              | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-models-v0-6.0.0-beta.6+0.79.0-1.19.4.jar                      |                                      |
|   185 | Quilted Fabric Networking (v0)                                        | quilted_fabric_networking_v0                          | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-networking-v0-6.0.0-beta.6+0.79.0-1.19.4.jar                  |                                      |
|   189 | Quilted Fabric Networking API (v1)                                    | quilted_fabric_networking_api_v1                      | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-networking-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar              |                                      |
|   210 | Quilted Fabric Object Builder API (v1)                                | quilted_fabric_object_builder_api_v1                  | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-object-builder-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar          |                                      |
|    85 | Quilted Fabric Particles (v1)                                         | quilted_fabric_particles_v1                           | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-particles-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                   |                                      |
|    84 | Quilted Fabric Recipe API (v1)                                        | quilted_fabric_recipe_api_v1                          | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-recipe-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                  |                                      |
|   145 | Quilted Fabric Registry Sync (v0)                                     | quilted_fabric_registry_sync_v0                       | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-registry-sync-v0-6.0.0-beta.6+0.79.0-1.19.4.jar               |                                      |
|   191 | Quilted Fabric Renderer - Indigo                                      | quilted_fabric_renderer_indigo                        | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-renderer-indigo-6.0.0-beta.6+0.79.0-1.19.4.jar                |                                      |
|   117 | Quilted Fabric Renderer API (v1)                                      | quilted_fabric_renderer_api_v1                        | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-renderer-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                |                                      |
|   143 | Quilted Fabric Renderer Registries (v1)                               | quilted_fabric_renderer_registries_v1                 | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-renderer-registries-v1-6.0.0-beta.6+0.79.0-1.19.4.jar         |                                      |
|   160 | Quilted Fabric Rendering (v0)                                         | quilted_fabric_rendering_v0                           | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-rendering-v0-6.0.0-beta.6+0.79.0-1.19.4.jar                   |                                      |
|   120 | Quilted Fabric Rendering (v1)                                         | quilted_fabric_rendering_v1                           | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-rendering-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                   |                                      |
|   169 | Quilted Fabric Rendering Data Attachment (v1)                         | quilted_fabric_rendering_data_attachment_v1           | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-rendering-data-attachment-v1-6.0.0-beta.6+0.79.0-1.19.4.jar   |                                      |
|   183 | Quilted Fabric Rendering Fluids (v1)                                  | quilted_fabric_rendering_fluids_v1                    | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-rendering-fluids-v1-6.0.0-beta.6+0.79.0-1.19.4.jar            |                                      |
|   148 | Quilted Fabric Resource Conditions API (v1)                           | quilted_fabric_resource_conditions_api_v1             | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-resource-conditions-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar     |                                      |
|   137 | Quilted Fabric Resource Loader (v0)                                   | quilted_fabric_resource_loader_v0                     | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-resource-loader-v0-6.0.0-beta.6+0.79.0-1.19.4.jar             |                                      |
|   107 | Quilted Fabric Screen API (v1)                                        | quilted_fabric_screen_api_v1                          | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-screen-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                  |                                      |
|    87 | Quilted Fabric Screen Handler API (v1)                                | quilted_fabric_screen_handler_api_v1                  | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-screen-handler-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar          |                                      |
|    89 | Quilted Fabric Sound API (v1)                                         | quilted_fabric_sound_api_v1                           | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-sound-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                   |                                      |
|   132 | Quilted Fabric Transfer API (v1)                                      | quilted_fabric_transfer_api_v1                        | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-transfer-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                |                                      |
|   115 | Quilted Fabric Transitive Access Wideners (v1)                        | quilted_fabric_transitive_access_wideners_v1          | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                      | /META-INF/jars/fabric-transitive-access-wideners-v1-6.0.0-beta.6+0.79.0-1.19.4.jar  |                                      |
|   106 | Raknetify (Fabric)                                                    | raknetify                                             | 0.1.0+alpha.5.73            | quilted_fabric_loader  | <mods>\\raknetify-fabric-0.1.0+alpha.5.73-all.jar                                                          |                                                                                     |                                      |
|    65 | Reese's Sodium Options                                                | reeses-sodium-options                                 | 1.5.0+mc1.19.4-build.72     | quilted_fabric_loader  | <mods>\\reeses_sodium_options-1.5.0+mc1.19.4-build.72.jar                                                  |                                                                                     |                                      |
|    79 | Reflect                                                               | net_lenni0451_reflect                                 | 1.1.0                       | quilted_fabric_loader  | <mods>\\ImmediatelyFast-1.1.12+1.19.4.jar                                                                  | /META-INF/jars/Reflect-1.1.0.jar                                                    |                                      |
|    55 | Runtime Resource Pack                                                 | advanced_runtime_resource_pack                        | 0.6.7                       | quilted_fabric_loader  | <mods>\\enhancedblockentities-0.8+1.19.3.jar                                                               | /META-INF/jars/arrp-0.6.7.jar                                                       |                                      |
|    37 | Satin                                                                 | satin                                                 | 1.9.0                       | quilted_fabric_loader  | <mods>\\effective-1.6+1.19.2.jar                                                                           | /META-INF/jars/satin-1.9.0.jar                                                      |                                      |
|   108 | Simple Voice Chat                                                     | voicechat                                             | 1.19.4-2.4.7                | quilted_fabric_loader  | <mods>\\voicechat-fabric-1.19.4-2.4.7.jar                                                                  |                                                                                     |                                      |
|    52 | Smooth chunk save Mod                                                 | smoothchunk                                           | 1.19.4-3.0                  | quilted_fabric_loader  | <mods>\\smoothchunk-fabric-1.19.4-3.0.jar                                                                  |                                                                                     |                                      |
|   187 | Sodium                                                                | sodium                                                | 0.4.10+build.24             | quilted_fabric_loader  | <mods>\\sodium-fabric-mc1.19.4-0.4.10+build.24.jar                                                         |                                                                                     |                                      |
|   188 | Sodium Extra                                                          | sodium-extra                                          | 0.4.18+mc1.19.4-build.100   | quilted_fabric_loader  | <mods>\\sodium-extra-0.4.18+mc1.19.4-build.100.jar                                                         |                                                                                     |                                      |
|   141 | Sound Physics Remastered                                              | sound_physics_remastered                              | 1.19.4-1.1.0                | quilted_fabric_loader  | <mods>\\soundphysics-fabric-1.19.4-1.1.0.jar                                                               |                                                                                     |                                      |
|   123 | SpruceUI                                                              | spruceui                                              | 4.2.0+1.19.4                | quilted_fabric_loader  | <mods>\\ok_zoomer-5.0.0-beta.11+1.19.4.jar                                                                 | /META-INF/jars/spruceui-4.2.0+1.19.4.jar                                            |                                      |
|   133 | Starlight                                                             | starlight                                             | 1.1.1+fabric.ae22326        | quilted_fabric_loader  | <mods>\\starlight-1.1.1+fabric.ae22326.jar                                                                 |                                                                                     |                                      |
|    17 | Tweakeroo                                                             | tweakeroo                                             | 0.16.0                      | quilted_fabric_loader  | <mods>\\tweakeroo-fabric-1.19.4-0.16.0.jar                                                                 |                                                                                     |                                      |
|    10 | WaveyCapes                                                            | waveycapes                                            | 1.3.2                       | quilted_fabric_loader  | <mods>\\waveycapes-fabric-1.3.2-mc1.19.3.jar                                                               |                                                                                     |                                      |
|    33 | WorldEdit                                                             | worldedit                                             | 7.2.14+6360-094b734         | quilted_fabric_loader  | <mods>\\worldedit-mod-7.2.14.jar                                                                           |                                                                                     |                                      |
|   175 | Xaero's Minimap                                                       | xaerominimap                                          | 23.4.2                      | quilted_fabric_loader  | <mods>\\Xaeros_Minimap_23.4.2_Fabric_1.19.4.jar                                                            |                                                                                     |                                      |
|   103 | Xaero's World Map                                                     | xaeroworldmap                                         | 1.30.2                      | quilted_fabric_loader  | <mods>\\XaerosWorldMap_1.30.2_Fabric_1.19.4.jar                                                            |                                                                                     |                                      |
|   156 | YetAnotherConfigLib                                                   | yet_another_config_lib                                | 2.5.1+1.19.4                | quilted_fabric_loader  | <mods>\\yet-another-config-lib-fabric-2.5.1+1.19.4.jar                                                     |                                                                                     |                                      |
|    61 | antlr4-runtime                                                        | org_antlr_antlr4-runtime                              | 4.11.1                      | quilted_fabric_loader  | <mods>\\iris-mc1.19.4-1.6.3.jar                                                                            | /META-INF/jars/antlr4-runtime-4.11.1.jar                                            |                                      |
|    19 | asyncutil                                                             | com_ibm_async_asyncutil                               | 0.1.0                       | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/asyncutil-0.1.0.jar                                                  |                                      |
|    14 | atomicfu-jvm                                                          | org_jetbrains_kotlinx_atomicfu-jvm                    | 0.20.2                      | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                     | /META-INF/jars/atomicfu-jvm-0.20.2.jar                                              |                                      |
|     1 | cloth-basic-math                                                      | cloth-basic-math                                      | 0.6.1                       | quilted_fabric_loader  | <mods>\\moreculling-1.19.4-0.17.0.jar                                                                      | /META-INF/jars/cloth-config-fabric-9.0.94.jar                                       | /META-INF/jars/basic-math-0.6.1.jar  |
|   152 | completeconfig-base                                                   | completeconfig-base                                   | 2.3.1                       | quilted_fabric_loader  | <mods>\\completeconfig-2.3.1.jar                                                                           | /META-INF/jars/completeconfig-base-2.3.1.jar                                        |                                      |
|    49 | completeconfig-gui-cloth                                              | completeconfig-gui-cloth                              | 2.3.1                       | quilted_fabric_loader  | <mods>\\completeconfig-2.3.1.jar                                                                           | /META-INF/jars/completeconfig-gui-cloth-2.3.1.jar                                   |                                      |
|    29 | completeconfig-gui-yacl                                               | completeconfig-gui-yacl                               | 2.3.1                       | quilted_fabric_loader  | <mods>\\completeconfig-2.3.1.jar                                                                           | /META-INF/jars/completeconfig-gui-yacl-2.3.1.jar                                    |                                      |
|    48 | conditional mixin                                                     | conditional-mixin                                     | 0.3.2                       | quilted_fabric_loader  | <mods>\\moreculling-1.19.4-0.17.0.jar                                                                      | /META-INF/jars/conditional-mixin-v0.3.2.jar                                         |                                      |
|     2 | config                                                                | com_typesafe_config                                   | 1.4.2                       | quilted_fabric_loader  | <mods>\\bobby-4.0.5.jar                                                                                    | /META-INF/jars/config-1.4.2.jar                                                     |                                      |
|    64 | configurate-core                                                      | org_spongepowered_configurate-core                    | 4.1.2                       | quilted_fabric_loader  | <mods>\\bobby-4.0.5.jar                                                                                    | /META-INF/jars/configurate-core-4.1.2.jar                                           |                                      |
|    58 | configurate-hocon                                                     | org_spongepowered_configurate-hocon                   | 4.1.2                       | quilted_fabric_loader  | <mods>\\bobby-4.0.5.jar                                                                                    | /META-INF/jars/configurate-hocon-4.1.2.jar                                          |                                      |
|    46 | core                                                                  | com_electronwill_night-config_core                    | 3.6.5                       | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/core-3.6.5.jar                                                       |                                      |
|    21 | exp4j                                                                 | net_objecthunter_exp4j                                | 0.4.8                       | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/exp4j-0.4.8.jar                                                      |                                      |
|    78 | geantyref                                                             | io_leangen_geantyref_geantyref                        | 1.3.13                      | quilted_fabric_loader  | <mods>\\bobby-4.0.5.jar                                                                                    | /META-INF/jars/geantyref-1.3.13.jar                                                 |                                      |
|    11 | glsl-transformer                                                      | io_github_douira_glsl-transformer                     | 2.0.0-pre13                 | quilted_fabric_loader  | <mods>\\iris-mc1.19.4-1.6.3.jar                                                                            | /META-INF/jars/glsl-transformer-2.0.0-pre13.jar                                     |                                      |
|    45 | httpmime                                                              | org_apache_httpcomponents_httpmime                    | 4.5.10                      | quilted_fabric_loader  | <mods>\\entity_texture_features_fabric_1.19.4-4.4.4.jar                                                    | /META-INF/jars/httpmime-4.5.10.jar                                                  |                                      |
|    30 | jcpp                                                                  | org_anarres_jcpp                                      | 1.4.14                      | quilted_fabric_loader  | <mods>\\iris-mc1.19.4-1.6.3.jar                                                                            | /META-INF/jars/jcpp-1.4.14.jar                                                      |                                      |
|    56 | kotlin-reflect                                                        | org_jetbrains_kotlin_kotlin-reflect                   | 1.8.21                      | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                     | /META-INF/jars/kotlin-reflect-1.8.21.jar                                            |                                      |
|    34 | kotlin-stdlib                                                         | org_jetbrains_kotlin_kotlin-stdlib                    | 1.8.21                      | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                     | /META-INF/jars/kotlin-stdlib-1.8.21.jar                                             |                                      |
|    59 | kotlin-stdlib-jdk7                                                    | org_jetbrains_kotlin_kotlin-stdlib-jdk7               | 1.8.21                      | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                     | /META-INF/jars/kotlin-stdlib-jdk7-1.8.21.jar                                        |                                      |
|    69 | kotlin-stdlib-jdk8                                                    | org_jetbrains_kotlin_kotlin-stdlib-jdk8               | 1.8.21                      | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                     | /META-INF/jars/kotlin-stdlib-jdk8-1.8.21.jar                                        |                                      |
|     5 | kotlinx-coroutines-core-jvm                                           | org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm     | 1.6.4                       | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                     | /META-INF/jars/kotlinx-coroutines-core-jvm-1.6.4.jar                                |                                      |
|    44 | kotlinx-coroutines-jdk8                                               | org_jetbrains_kotlinx_kotlinx-coroutines-jdk8         | 1.6.4                       | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                     | /META-INF/jars/kotlinx-coroutines-jdk8-1.6.4.jar                                    |                                      |
|    72 | kotlinx-datetime-jvm                                                  | org_jetbrains_kotlinx_kotlinx-datetime-jvm            | 0.4.0                       | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                     | /META-INF/jars/kotlinx-datetime-jvm-0.4.0.jar                                       |                                      |
|    23 | kotlinx-serialization-cbor-jvm                                        | org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm  | 1.5.0                       | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                     | /META-INF/jars/kotlinx-serialization-cbor-jvm-1.5.0.jar                             |                                      |
|    36 | kotlinx-serialization-core-jvm                                        | org_jetbrains_kotlinx_kotlinx-serialization-core-jvm  | 1.5.0                       | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                     | /META-INF/jars/kotlinx-serialization-core-jvm-1.5.0.jar                             |                                      |
|    31 | kotlinx-serialization-json-jvm                                        | org_jetbrains_kotlinx_kotlinx-serialization-json-jvm  | 1.5.0                       | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                     | /META-INF/jars/kotlinx-serialization-json-jvm-1.5.0.jar                             |                                      |
|    28 | recipecache                                                           | recipecache                                           | 0.2.0-1.19                  | quilted_fabric_loader  | <mods>\\recipecache-0.2.0-1.19.jar                                                                         |                                                                                     |                                      |
|    66 | threadly                                                              | org_threadly_threadly                                 | 7.0                         | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/threadly-7.0.jar                                                     |                                      |
|    71 | toml                                                                  | com_electronwill_night-config_toml                    | 3.6.5                       | quilted_fabric_loader  | <mods>\\c2me-fabric-mc1.19.4-0.2.0+alpha.10.51.jar                                                         | /META-INF/jars/toml-3.6.5.jar                                                       |                                      |
|    35 | toml4j                                                                | com_moandjiezana_toml_toml4j                          | 0.7.2                       | quilted_fabric_loader  | <mods>\\dynamic-fps-2.2.0.jar                                                                              | /META-INF/jars/toml4j-0.7.2.jar                                                     |                                      |
|    63 | velocity-native                                                       | com_velocitypowered_velocity-native                   | 3.2.0-SNAPSHOT              | quilted_fabric_loader  | <mods>\\krypton-0.2.2.jar                                                                                  | /META-INF/jars/velocity-native-3.2.0-SNAPSHOT.jar                                   |                                      |
|------:|-----------------------------------------------------------------------|-------------------------------------------------------|-----------------------------|------------------------|-----------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|--------------------------------------|


---- end of report ----`