export const ClassicQuiltLog = `---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-05-20 00:20:45
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_309 failed
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:456)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:246)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:164)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228)
\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
\tat net.minecraft.class_310.<init>(class_310.java:514)
\tat net.minecraft.client.main.Main.main(Main.java:198)
\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)
\tat org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
\tat org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
\tat org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
\tat org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
\tat org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
\tat org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:451)
\t... 14 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [#cloth-client-events-v0:cloth-client-events-v0.mixins.json:MixinKeyboard from mod cloth-client-events-v0] from phase [DEFAULT] in config [#cloth-client-events-v0:cloth-client-events-v0.mixins.json] FAILED during APPLY
\tat org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
\tat org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
\tat org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
\t... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_1683 was not located in the target class net.minecraft.class_309. Using refmap cloth-client-events-v0-cloth-client-events-v0-refmap.json
\tat org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:624)
\tat org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302)
\tat org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
\tat org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
\tat org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
\tat org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
\tat org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
\tat org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
\t... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:456)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:246)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:164)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228)
\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
\tat net.minecraft.class_310.<init>(class_310.java:514)

-- Initialization --
Details:
\tModules: 
\t\tADVAPI32.dll:Erweiterte Windows 32 Base-API:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tCOMCTL32.dll:Bibliothek für Steuerelemente:6.10 (WinBuild.160101.0800):Microsoft Corporation
\t\tCRYPT32.dll:Krypto-API32:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tCRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tCRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tCoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
\t\tCoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.22621.1635:Microsoft Corporation
\t\tDBGHELP.DLL:Windows Image Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tDEVOBJ.dll:Device Information Set DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
\t\tDNSAPI.dll:DNS-Client-API-DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tGDI32.dll:GDI Client DLL:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
\t\tGLU32.dll:OpenGL-Hilfsprogrammbibliotheks-DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tIMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
\t\tIPHLPAPI.DLL:IP-Hilfs-API:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tKERNEL32.DLL:Client-DLL für Windows NT-Basis-API:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tKERNELBASE.dll:Client-DLL für Windows NT-Basis-API:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tMSASN1.dll:ASN.1 Runtime APIs:10.0.22621.819 (WinBuild.160101.0800):Microsoft Corporation
\t\tMSCTF.dll:MSCTF-Server-DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tMpOav.dll:IOfficeAntiVirus Module:4.18.2304.8 (WinBuild.160101.0800):Microsoft Corporation
\t\tNSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tNTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tOLEAUT32.dll:OLEAUT32.DLL:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
\t\tOle32.dll:Microsoft OLE für Windows:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tPSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tPdh.dll:Windows Unterstützungs-DLL für Leistungsdaten:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tRPCRT4.dll:Remoteprozeduraufruf-Laufzeitumgebung:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tSETUPAPI.dll:Windows Setup-API:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tSHCORE.dll:SHCORE:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tSHELL32.dll:Allgemeine Windows-Shell-DLL:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
\t\tUMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tUSER32.dll:Client-DLL für Windows USER-API (mehrere Benutzer):10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tUSERENV.dll:Userenv:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tVCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
\t\tVERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tWINHTTP.dll:Windows HTTP-Dienste:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tWINMM.dll:MCI API-DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tWINSTA.dll:Winstation Library:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
\t\tWINTRUST.dll:Microsoft Trust Verification APIs:10.0.22621.1485 (WinBuild.160101.0800):Microsoft Corporation
\t\tWS2_32.dll:Windows Socket 2.0-32-Bit-DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tWSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tWTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tamsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tbcrypt.dll:Bibliothek mit kryptografischen Primitiven von Windows:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tbcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
\t\tcfgmgr32.dll:Configuration Manager DLL:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
\t\tclbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
\t\tcombase.dll:Microsoft COM für Windows:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tcryptnet.dll:Crypto Network Related API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tdbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tdhcpcsvc.DLL:DHCP Clientdienst:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tdhcpcsvc6.DLL:DHCPv6-Client:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tdinput8.dll:Microsoft DirectInput:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tdrvstore.dll:Driver Store API:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
\t\tdwmapi.dll:Microsoft Desktopfenster-Manager-API:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tdxcore.dll:DXCore:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
\t\tfwpuclnt.dll:FWP/IPsec Benutzermodus-API:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tgdi32full.dll:GDI Client DLL:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
\t\tglfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
\t\ticm32.dll:Microsoft Color Management Module (CMM):10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
\t\tinputhost.dll:InputHost:10.0.22621.1344 (WinBuild.160101.0800):Microsoft Corporation
\t\tjava.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
\t\tjavaw.exe:OpenJDK Platform binary:17.0.3.0:Microsoft
\t\tjemalloc.dll
\t\tjimage.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
\t\tjli.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
\t\tjna16181147685358766156.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
\t\tjsvml.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
\t\tjvm.dll:OpenJDK 64-Bit server VM:17.0.3.0:Microsoft
\t\tkernel.appcore.dll:AppModel API Host:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tlwjgl.dll
\t\tlwjgl_opengl.dll
\t\tlwjgl_stb.dll
\t\tmanagement.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
\t\tmanagement_ext.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
\t\tmscms.dll:Microsoft-Farbabstimmungssystem-DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tmsvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
\t\tmsvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
\t\tmsvcrt.dll:Windows NT CRT DLL:7.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
\t\tmswsock.dll:Microsoft Windows Sockets 2.0-Dienstanbieter:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tnapinsp.dll:E-Mail-Namenshimanbieter:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tncrypt.dll:Windows NCrypt-Router:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tnet.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
\t\tnio.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
\t\tnlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tntdll.dll:DLL für NT-Layer:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tntmarta.dll:Windows NT MARTA-Anbieter:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tnvoglv64.dll:NVIDIA Compatible OpenGL ICD:31.0.15.2824:NVIDIA Corporation
\t\tnvspcap64.dll:NVIDIA Game Proxy:3.27.0.112:NVIDIA Corporation
\t\topengl32.dll:OpenGL Client DLL:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
\t\tperfos.dll:DLL für Windows-Systemleistungsobjekte:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tpfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tpnrpnsp.dll:PNRP-Namespaceanbieter:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tpowrprof.dll:Power Profile Helper DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tprofapi.dll:User Profile Basic API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\trasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\trsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tsechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\tshlwapi.dll:Shell Light-weight-Hilfsprogrammbibliothek:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tsunmscapi.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
\t\tsymamsi.dll:Symantec AMSI provider:15.7.12.41:Broadcom
\t\ttextinputframework.dll:"TextInputFramework.DYNLINK":10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
\t\tucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.608 (WinBuild.160101.0800):Microsoft Corporation
\t\tuxtheme.dll:Microsoft UxTheme-Bibliothek:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tvcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
\t\tverify.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
\t\twin32u.dll:Win32u:10.0.22621.1635 (WinBuild.160101.0800):Microsoft Corporation
\t\twindows.storage.dll:Microsoft WinRT Storage-API:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\twinrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\twintypes.dll:Windows-Basistypen-DLL:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\twldp.dll:Windows-Sperrungsrichtlinie:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\twshbth.dll:Windows Sockets Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\twshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
\t\txinput1_4.dll:API für Microsoft Common Controller:10.0.22621.1554 (WinBuild.160101.0800):Microsoft Corporation
\t\tzip.dll:OpenJDK Platform binary:17.0.3.0:Microsoft
Stacktrace:
\tat net.minecraft.client.main.Main.main(Main.java:198)
\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)
\tat org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
\tat org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
\tat org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
\tMinecraft Version: 1.19.4
\tMinecraft Version ID: 1.19.4
\tOperating System: Windows 10 (amd64) version 10.0
\tJava Version: 17.0.3, Microsoft
\tJava VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
\tMemory: 456732920 bytes (435 MiB) / 905969664 bytes (864 MiB) up to 2147483648 bytes (2048 MiB)
\tCPUs: 12
\tProcessor Vendor: GenuineIntel
\tProcessor Name: 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
\tIdentifier: Intel64 Family 6 Model 167 Stepping 1
\tMicroarchitecture: Rocket Lake
\tFrequency (GHz): 2.59
\tNumber of physical packages: 1
\tNumber of physical CPUs: 6
\tNumber of logical CPUs: 12
\tGraphics card #0 name: NVIDIA GeForce GTX 1650
\tGraphics card #0 vendor: NVIDIA (0x10de)
\tGraphics card #0 VRAM (MB): 4095.00
\tGraphics card #0 deviceId: 0x1f82
\tGraphics card #0 versionInfo: DriverVersion=31.0.15.2824
\tMemory slot #0 capacity (MB): 8192.00
\tMemory slot #0 clockSpeed (GHz): 3.20
\tMemory slot #0 type: DDR4
\tMemory slot #1 capacity (MB): 8192.00
\tMemory slot #1 clockSpeed (GHz): 3.20
\tMemory slot #1 type: DDR4
\tVirtual memory max (MB): 28525.39
\tVirtual memory used (MB): 12904.73
\tSwap memory total (MB): 12288.00
\tSwap memory used (MB): 457.89
\tJVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
\tQuilt Mods: 
\t\t| Index | Mod                                               | ID                                                    | Version                     | Plugin                 | File(s)                                                                                                                                         | Sub-Files                                                                           |
\t\t|------:|---------------------------------------------------|-------------------------------------------------------|-----------------------------|------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|
\t\t|    65 | Cloth API                                         | cloth-api                                             | 4.0.65                      | quilted_fabric_loader  | <mods>\\cloth-api-4.0.65.jar                                                                                                                     |                                                                                     |
\t\t|   100 | Cloth Client Events v0                            | cloth-client-events-v0                                | 4.0.65                      | quilted_fabric_loader  | <mods>\\cloth-api-4.0.65.jar                                                                                                                     | /META-INF/jars/cloth-client-events-v0-4.0.65.jar                                    |
\t\t|    52 | Cloth Common Events v1                            | cloth-common-events-v1                                | 4.0.65                      | quilted_fabric_loader  | <mods>\\cloth-api-4.0.65.jar                                                                                                                     | /META-INF/jars/cloth-common-events-v1-4.0.65.jar                                    |
\t\t|   127 | Cloth Scissors API v1                             | cloth-scissors-api-v1                                 | 4.0.65                      | quilted_fabric_loader  | <mods>\\cloth-api-4.0.65.jar                                                                                                                     | /META-INF/jars/cloth-scissors-api-v1-4.0.65.jar                                     |
\t\t|    62 | Cloth Utils v1                                    | cloth-utils-v1                                        | 4.0.65                      | quilted_fabric_loader  | <mods>\\cloth-api-4.0.65.jar                                                                                                                     | /META-INF/jars/cloth-utils-v1-4.0.65.jar                                            |
\t\t|    19 | Coat                                              | coat                                                  | 1.0.0-beta.19+mc1.19.3      | quilted_fabric_loader  | <mods>\\completeconfig-2.3.0.jar                                                                                                                 | /META-INF/jars/coat-1.19-1.0.0-beta.19+mc1.19.3.jar                                 |
\t\t|    25 | CompleteConfig                                    | completeconfig                                        | 2.3.0                       | quilted_fabric_loader  | <mods>\\completeconfig-2.3.0.jar                                                                                                                 |                                                                                     |
\t\t|    17 | Dynamic FPS                                       | dynamicfps                                            | 2.2.0                       | quilted_fabric_loader  | <mods>\\dynamic-fps-2.2.0.jar                                                                                                                    |                                                                                     |
\t\t|   118 | Fabric Language Kotlin                            | fabric-language-kotlin                                | 1.9.4+kotlin.1.8.21         | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                                                           |                                                                                     |
\t\t|   122 | FiveOneFourOneEight                               | fiveonefouroneeight                                   | 1.0.0                       | quilted_fabric_loader  | <mods>\\fiveonefouroneeight-1.0.0.jar                                                                                                            |                                                                                     |
\t\t|    10 | Indium                                            | indium                                                | 1.0.15+mc1.19.4             | quilted_fabric_loader  | <mods>\\indium-1.0.15+mc1.19.4.jar                                                                                                               |                                                                                     |
\t\t|    24 | Krypton                                           | krypton                                               | 0.2.1                       | quilted_fabric_loader  | <mods>\\krypton-0.2.1.jar                                                                                                                        |                                                                                     |
\t\t|     0 | LazyDFU                                           | lazydfu                                               | 0.1.3                       | quilted_fabric_loader  | <mods>\\lazydfu-0.1.3.jar                                                                                                                        |                                                                                     |
\t\t|    48 | Lithium                                           | lithium                                               | 0.11.1                      | quilted_fabric_loader  | <mods>\\lithium-fabric-mc1.19.4-0.11.1.jar                                                                                                       |                                                                                     |
\t\t|    22 | MaLiLib                                           | malilib                                               | 0.15.4                      | quilted_fabric_loader  | <mods>\\malilib-fabric-1.19.4-0.15.4.jar                                                                                                         |                                                                                     |
\t\t|    77 | Marlow's Crystal Optimizer                        | marlows-crystal-optimizer                             | 1.0.0                       | quilted_fabric_loader  | <mods>\\Marlows-Crystal-Optimizer-1.19.X.jar                                                                                                     |                                                                                     |
\t\t|     2 | MidnightLib                                       | midnightlib                                           | 1.3.0                       | quilted_fabric_loader  | <mods>\\midnightlib-fabric-1.3.0.jar                                                                                                             |                                                                                     |
\t\t|    33 | Minecraft                                         | minecraft                                             | 1.19.4                      | quilt_loader           | <game>\\.quilt\\remappedJars\\minecraft-1.19.4-0.18.10\\client-intermediary.jar                                                                     |                                                                                     |
\t\t|     3 | MiniHUD                                           | minihud                                               | 0.26.2                      | quilted_fabric_loader  | <mods>\\minihud-fabric-1.19.4-0.26.2.jar                                                                                                         |                                                                                     |
\t\t|    31 | Mod Menu                                          | modmenu                                               | 6.2.2                       | quilted_fabric_loader  | <mods>\\modmenu-6.2.2.jar                                                                                                                        |                                                                                     |
\t\t|     8 | MoreChatHistory                                   | morechathistory                                       | 1.1.1                       | quilted_fabric_loader  | <mods>\\morechathistory-1.19.1-1.1.1.jar                                                                                                         |                                                                                     |
\t\t|    26 | NoHurtCam                                         | nohurtcam                                             | 1                           | quilted_fabric_loader  | <mods>\\noHurtCam-1.jar                                                                                                                          |                                                                                     |
\t\t|    79 | OpenJDK 64-Bit Server VM                          | java                                                  | 17                          | quilt_loader           | <user>\\AppData\\Local\\Packages\\Microsoft.4297127D64EC6_8wekyb3d8bbwe\\LocalCache\\Local\\runtime\\java-runtime-gamma\\windows-x64\\java-runtime-gamma  |                                                                                     |
\t\t|    43 | Quilt Advancement API                             | quilt_advancement                                     | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/advancement-5.0.0-beta.5+1.19.4.jar                                  |
\t\t|    34 | Quilt Base API                                    | quilt_base                                            | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/qsl_base-5.0.0-beta.5+1.19.4.jar                                     |
\t\t|    80 | Quilt Biome API                                   | quilt_biome                                           | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/biome-5.0.0-beta.5+1.19.4.jar                                        |
\t\t|    81 | Quilt Block Content Registry API                  | quilt_block_content_registry                          | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/block_content_registry-5.0.0-beta.5+1.19.4.jar                       |
\t\t|    63 | Quilt Block Entity API                            | quilt_block_entity                                    | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/block_entity-5.0.0-beta.5+1.19.4.jar                                 |
\t\t|    45 | Quilt Block Extensions API                        | quilt_block_extensions                                | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/block_extensions-5.0.0-beta.5+1.19.4.jar                             |
\t\t|    38 | Quilt Chat API                                    | quilt_chat                                            | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/chat-5.0.0-beta.5+1.19.4.jar                                         |
\t\t|   119 | Quilt Client Command API                          | quilt_client_command                                  | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/client_command-5.0.0-beta.5+1.19.4.jar                               |
\t\t|    64 | Quilt Command API                                 | quilt_command                                         | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/command-5.0.0-beta.5+1.19.4.jar                                      |
\t\t|    58 | Quilt Crash Info                                  | quilt_crash_info                                      | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/crash_info-5.0.0-beta.5+1.19.4.jar                                   |
\t\t|    32 | Quilt Dimension API                               | quilt_dimension                                       | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/dimension-5.0.0-beta.5+1.19.4.jar                                    |
\t\t|    39 | Quilt Entity API                                  | quilt_entity                                          | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/entity-5.0.0-beta.5+1.19.4.jar                                       |
\t\t|    68 | Quilt Entity Events                               | quilt_entity_events                                   | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/entity_events-5.0.0-beta.5+1.19.4.jar                                |
\t\t|    83 | Quilt Entity Networking API                       | quilt_entity_networking                               | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/entity_networking-5.0.0-beta.5+1.19.4.jar                            |
\t\t|   128 | Quilt Entity Rendering API                        | quilt_entity_rendering                                | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/entity_rendering-5.0.0-beta.5+1.19.4.jar                             |
\t\t|    96 | Quilt Item Content Registry API                   | quilt_item_content_registry                           | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/item_content_registry-5.0.0-beta.5+1.19.4.jar                        |
\t\t|    59 | Quilt Item Extensions API                         | quilt_item_extensions                                 | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/item_extensions-5.0.0-beta.5+1.19.4.jar                              |
\t\t|    98 | Quilt Item Setting API                            | quilt_item_setting                                    | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/item_setting-5.0.0-beta.5+1.19.4.jar                                 |
\t\t|    54 | Quilt Lifecycle Events                            | quilt_lifecycle_events                                | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/lifecycle_events-5.0.0-beta.5+1.19.4.jar                             |
\t\t|    55 | Quilt Loader                                      | quilt_loader                                          | 0.18.10                     | quilt_loader           | <user>\\AppData\\Roaming\\.minecraft\\libraries\\org\\quiltmc\\quilt-loader\\0.18.10\\quilt-loader-0.18.10.jar                                           |                                                                                     |
\t\t|    88 | Quilt Multipart Entity API                        | quilt_entity_multipart                                | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/multipart-5.0.0-beta.5+1.19.4.jar                                    |
\t\t|   131 | Quilt Networking                                  | quilt_networking                                      | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/networking-5.0.0-beta.5+1.19.4.jar                                   |
\t\t|    51 | Quilt Point of Interest API                       | quilt_point_of_interest                               | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/point_of_interest-5.0.0-beta.5+1.19.4.jar                            |
\t\t|    97 | Quilt Recipe API                                  | quilt_recipe                                          | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/recipe-5.0.0-beta.5+1.19.4.jar                                       |
\t\t|    93 | Quilt Registry API                                | quilt_registry                                        | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/registry-5.0.0-beta.5+1.19.4.jar                                     |
\t\t|    75 | Quilt Registry Entry Attachment                   | quilt_registry_entry_attachment                       | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/registry_entry_attachment-5.0.0-beta.5+1.19.4.jar                    |
\t\t|    90 | Quilt Resource Loader                             | quilt_resource_loader                                 | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/resource_loader-5.0.0-beta.5+1.19.4.jar                              |
\t\t|   102 | Quilt Screen API                                  | quilt_screen                                          | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/screen-5.0.0-beta.5+1.19.4.jar                                       |
\t\t|   115 | Quilt Status Effect API                           | quilt_status_effect                                   | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/status_effect-5.0.0-beta.5+1.19.4.jar                                |
\t\t|    99 | Quilt Surface Rule API                            | quilt_surface_rule                                    | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/surface_rule-5.0.0-beta.5+1.19.4.jar                                 |
\t\t|    50 | Quilt Tags API                                    | quilt_tags                                            | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/tags-5.0.0-beta.5+1.19.4.jar                                         |
\t\t|    85 | Quilt Testing API                                 | quilt_testing                                         | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/testing-5.0.0-beta.5+1.19.4.jar                                      |
\t\t|    73 | Quilt Tooltip API                                 | quilt_tooltip                                         | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/tooltip-5.0.0-beta.5+1.19.4.jar                                      |
\t\t|   105 | Quilt Vehicle API                                 | quilt_vehicle                                         | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/vehicle-5.0.0-beta.5+1.19.4.jar                                      |
\t\t|   103 | Quilt Villager API                                | quilt_villager                                        | 5.0.0-beta.5+1.19.4         | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/villager-5.0.0-beta.5+1.19.4.jar                                     |
\t\t|    60 | Quilted Fabric API                                | quilted_fabric_api                                    | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            |                                                                                     |
\t\t|   112 | Quilted Fabric API Base                           | quilted_fabric_api_base                               | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-api-base-6.0.0-beta.6+0.79.0-1.19.4.jar                       |
\t\t|    66 | Quilted Fabric API Lookup API (v1)                | quilted_fabric_api_lookup_api_v1                      | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-api-lookup-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar              |
\t\t|   120 | Quilted Fabric Biome API (v1)                     | quilted_fabric_biome_api_v1                           | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-biome-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                   |
\t\t|    61 | Quilted Fabric Block API (v1)                     | quilted_fabric_block_api_v1                           | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-block-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                   |
\t\t|    86 | Quilted Fabric BlockRenderLayer Registration (v1) | quilted_fabric_blockrenderlayer_v1                    | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-blockrenderlayer-v1-6.0.0-beta.6+0.79.0-1.19.4.jar            |
\t\t|   114 | Quilted Fabric Client Tags                        | quilted_fabric_client_tags_api_v1                     | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-client-tags-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar             |
\t\t|   113 | Quilted Fabric Command API (v1)                   | quilted_fabric_command_api_v1                         | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-command-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                 |
\t\t|   130 | Quilted Fabric Command API (v2)                   | quilted_fabric_command_api_v2                         | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-command-api-v2-6.0.0-beta.6+0.79.0-1.19.4.jar                 |
\t\t|    49 | Quilted Fabric Commands (v0)                      | quilted_fabric_commands_v0                            | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-commands-v0-6.0.0-beta.6+0.79.0-1.19.4.jar                    |
\t\t|    92 | Quilted Fabric Containers (v0)                    | quilted_fabric_containers_v0                          | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-containers-v0-6.0.0-beta.6+0.79.0-1.19.4.jar                  |
\t\t|    95 | Quilted Fabric Content Registries (v0)            | quilted_fabric_content_registries_v0                  | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-content-registries-v0-6.0.0-beta.6+0.79.0-1.19.4.jar          |
\t\t|   126 | Quilted Fabric Convention Tags API (v1)           | quilted_fabric_convention_tags_api_v1                 | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-convention-tags-v1-6.0.0-beta.6+0.79.0-1.19.4.jar             |
\t\t|    70 | Quilted Fabric Crash Report Info (v1)             | quilted_fabric_crash_report_info_v1                   | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-crash-report-info-v1-6.0.0-beta.6+0.79.0-1.19.4.jar           |
\t\t|   123 | Quilted Fabric Data Generation API (v1)           | quilted_fabric_data_generation_api_v1                 | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-data-generation-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar         |
\t\t|    41 | Quilted Fabric Dimensions API (v1)                | quilted_fabric_dimensions_v1                          | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-dimensions-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                  |
\t\t|    76 | Quilted Fabric Entity Events (v1)                 | quilted_fabric_entity_events_v1                       | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-entity-events-v1-6.0.0-beta.6+0.79.0-1.19.4.jar               |
\t\t|   109 | Quilted Fabric Events Interaction (v0)            | quilted_fabric_events_interaction_v0                  | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-events-interaction-v0-6.0.0-beta.6+0.79.0-1.19.4.jar          |
\t\t|   101 | Quilted Fabric Events Lifecycle (v0)              | quilted_fabric_events_lifecycle_v0                    | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-events-lifecycle-v0-6.0.0-beta.6+0.79.0-1.19.4.jar            |
\t\t|    44 | Quilted Fabric Game Rule API (v1)                 | quilted_fabric_game_rule_api_v1                       | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-game-rule-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar               |
\t\t|   124 | Quilted Fabric Item API (v1)                      | quilted_fabric_item_api_v1                            | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-item-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                    |
\t\t|    82 | Quilted Fabric Item Group API (v1)                | quilted_fabric_item_group_api_v1                      | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-item-group-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar              |
\t\t|    42 | Quilted Fabric Key Binding API (v1)               | quilted_fabric_key_binding_api_v1                     | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-key-binding-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar             |
\t\t|    84 | Quilted Fabric Key Bindings (v0)                  | quilted_fabric_keybindings_v0                         | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-keybindings-v0-6.0.0-beta.6+0.79.0-1.19.4.jar                 |
\t\t|    67 | Quilted Fabric Lifecycle Events (v1)              | quilted_fabric_lifecycle_events_v1                    | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-lifecycle-events-v1-6.0.0-beta.6+0.79.0-1.19.4.jar            |
\t\t|   108 | Quilted Fabric Loot API (v2)                      | quilted_fabric_loot_api_v2                            | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-loot-api-v2-6.0.0-beta.6+0.79.0-1.19.4.jar                    |
\t\t|    74 | Quilted Fabric Loot Tables (v1)                   | quilted_fabric_loot_tables_v1                         | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-loot-tables-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                 |
\t\t|    87 | Quilted Fabric Message API (v1)                   | quilted_fabric_message_api_v1                         | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-message-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                 |
\t\t|    53 | Quilted Fabric Mining Level API (v1)              | quilted_fabric_mining_level_api_v1                    | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-mining-level-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar            |
\t\t|   111 | Quilted Fabric Models (v0)                        | quilted_fabric_models_v0                              | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-models-v0-6.0.0-beta.6+0.79.0-1.19.4.jar                      |
\t\t|   110 | Quilted Fabric Networking (v0)                    | quilted_fabric_networking_v0                          | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-networking-v0-6.0.0-beta.6+0.79.0-1.19.4.jar                  |
\t\t|    37 | Quilted Fabric Networking API (v1)                | quilted_fabric_networking_api_v1                      | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-networking-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar              |
\t\t|   129 | Quilted Fabric Object Builder API (v1)            | quilted_fabric_object_builder_api_v1                  | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-object-builder-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar          |
\t\t|    56 | Quilted Fabric Particles (v1)                     | quilted_fabric_particles_v1                           | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-particles-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                   |
\t\t|    78 | Quilted Fabric Recipe API (v1)                    | quilted_fabric_recipe_api_v1                          | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-recipe-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                  |
\t\t|   107 | Quilted Fabric Registry Sync (v0)                 | quilted_fabric_registry_sync_v0                       | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-registry-sync-v0-6.0.0-beta.6+0.79.0-1.19.4.jar               |
\t\t|    89 | Quilted Fabric Renderer - Indigo                  | quilted_fabric_renderer_indigo                        | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-renderer-indigo-6.0.0-beta.6+0.79.0-1.19.4.jar                |
\t\t|   106 | Quilted Fabric Renderer API (v1)                  | quilted_fabric_renderer_api_v1                        | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-renderer-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                |
\t\t|   116 | Quilted Fabric Renderer Registries (v1)           | quilted_fabric_renderer_registries_v1                 | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-renderer-registries-v1-6.0.0-beta.6+0.79.0-1.19.4.jar         |
\t\t|   104 | Quilted Fabric Rendering (v0)                     | quilted_fabric_rendering_v0                           | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-rendering-v0-6.0.0-beta.6+0.79.0-1.19.4.jar                   |
\t\t|    40 | Quilted Fabric Rendering (v1)                     | quilted_fabric_rendering_v1                           | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-rendering-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                   |
\t\t|   121 | Quilted Fabric Rendering Data Attachment (v1)     | quilted_fabric_rendering_data_attachment_v1           | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-rendering-data-attachment-v1-6.0.0-beta.6+0.79.0-1.19.4.jar   |
\t\t|    36 | Quilted Fabric Rendering Fluids (v1)              | quilted_fabric_rendering_fluids_v1                    | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-rendering-fluids-v1-6.0.0-beta.6+0.79.0-1.19.4.jar            |
\t\t|    69 | Quilted Fabric Resource Conditions API (v1)       | quilted_fabric_resource_conditions_api_v1             | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-resource-conditions-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar     |
\t\t|    71 | Quilted Fabric Resource Loader (v0)               | quilted_fabric_resource_loader_v0                     | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-resource-loader-v0-6.0.0-beta.6+0.79.0-1.19.4.jar             |
\t\t|    35 | Quilted Fabric Screen API (v1)                    | quilted_fabric_screen_api_v1                          | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-screen-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                  |
\t\t|    47 | Quilted Fabric Screen Handler API (v1)            | quilted_fabric_screen_handler_api_v1                  | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-screen-handler-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar          |
\t\t|    46 | Quilted Fabric Sound API (v1)                     | quilted_fabric_sound_api_v1                           | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-sound-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                   |
\t\t|    91 | Quilted Fabric Transfer API (v1)                  | quilted_fabric_transfer_api_v1                        | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-transfer-api-v1-6.0.0-beta.6+0.79.0-1.19.4.jar                |
\t\t|    30 | Quilted Fabric Transitive Access Wideners (v1)    | quilted_fabric_transitive_access_wideners_v1          | 6.0.0-beta.6+0.79.0-1.19.4  | quilt_loader           | <mods>\\qfapi-6.0.0-beta.6_qsl-5.0.0-beta.5_fapi-0.79.0_mc-1.19.4.jar                                                                            | /META-INF/jars/fabric-transitive-access-wideners-v1-6.0.0-beta.6+0.79.0-1.19.4.jar  |
\t\t|    21 | Replay Mod                                        | replaymod                                             | 1.19.4-2.6.12               | quilted_fabric_loader  | <mods>\\replaymod-1.19.4-2.6.12.jar                                                                                                              |                                                                                     |
\t\t|     5 | Runtime Resource Pack                             | advanced_runtime_resource_pack                        | 0.6.7                       | quilted_fabric_loader  | <mods>\\arrp-0.6.7.jar                                                                                                                           |                                                                                     |
\t\t|    94 | Smooth Boot                                       | smoothboot                                            | 1.19.4-1.7.0                | quilted_fabric_loader  | <mods>\\smoothboot-fabric-1.19.4-1.7.0.jar                                                                                                       |                                                                                     |
\t\t|   117 | Sodium                                            | sodium                                                | 0.4.10+build.24             | quilted_fabric_loader  | <mods>\\sodium-fabric-mc1.19.4-0.4.10+build.24.jar                                                                                               |                                                                                     |
\t\t|    72 | Starlight                                         | starlight                                             | 1.1.1+fabric.ae22326        | quilted_fabric_loader  | <mods>\\starlight-1.1.1+fabric.ae22326.jar                                                                                                       |                                                                                     |
\t\t|   125 | ToolTip Fix                                       | tooltipfix                                            | 1.1.1-1.19.3                | quilted_fabric_loader  | <mods>\\tooltipfix-1.1.1-1.19.3.jar                                                                                                              |                                                                                     |
\t\t|    14 | atomicfu-jvm                                      | org_jetbrains_kotlinx_atomicfu-jvm                    | 0.20.2                      | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                                                           | /META-INF/jars/atomicfu-jvm-0.20.2.jar                                              |
\t\t|    23 | cloth-basic-math                                  | cloth-basic-math                                      | 0.6.1                       | quilted_fabric_loader  | <mods>\\cloth-api-4.0.65.jar                                                                                                                     | /META-INF/jars/basic-math-0.6.1.jar                                                 |
\t\t|    57 | completeconfig-base                               | completeconfig-base                                   | 2.3.0                       | quilted_fabric_loader  | <mods>\\completeconfig-2.3.0.jar                                                                                                                 | /META-INF/jars/completeconfig-base-2.3.0.jar                                        |
\t\t|     6 | completeconfig-gui-cloth                          | completeconfig-gui-cloth                              | 2.3.0                       | quilted_fabric_loader  | <mods>\\completeconfig-2.3.0.jar                                                                                                                 | /META-INF/jars/completeconfig-gui-cloth-2.3.0.jar                                   |
\t\t|    18 | completeconfig-gui-coat                           | completeconfig-gui-coat                               | 2.3.0                       | quilted_fabric_loader  | <mods>\\completeconfig-2.3.0.jar                                                                                                                 | /META-INF/jars/completeconfig-gui-coat-2.3.0.jar                                    |
\t\t|    15 | completeconfig-gui-yacl                           | completeconfig-gui-yacl                               | 2.3.0                       | quilted_fabric_loader  | <mods>\\completeconfig-2.3.0.jar                                                                                                                 | /META-INF/jars/completeconfig-gui-yacl-2.3.0.jar                                    |
\t\t|     4 | kotlin-reflect                                    | org_jetbrains_kotlin_kotlin-reflect                   | 1.8.21                      | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                                                           | /META-INF/jars/kotlin-reflect-1.8.21.jar                                            |
\t\t|     1 | kotlin-stdlib                                     | org_jetbrains_kotlin_kotlin-stdlib                    | 1.8.21                      | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                                                           | /META-INF/jars/kotlin-stdlib-1.8.21.jar                                             |
\t\t|    12 | kotlin-stdlib-jdk7                                | org_jetbrains_kotlin_kotlin-stdlib-jdk7               | 1.8.21                      | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                                                           | /META-INF/jars/kotlin-stdlib-jdk7-1.8.21.jar                                        |
\t\t|    13 | kotlin-stdlib-jdk8                                | org_jetbrains_kotlin_kotlin-stdlib-jdk8               | 1.8.21                      | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                                                           | /META-INF/jars/kotlin-stdlib-jdk8-1.8.21.jar                                        |
\t\t|    11 | kotlinx-coroutines-core-jvm                       | org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm     | 1.6.4                       | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                                                           | /META-INF/jars/kotlinx-coroutines-core-jvm-1.6.4.jar                                |
\t\t|     7 | kotlinx-coroutines-jdk8                           | org_jetbrains_kotlinx_kotlinx-coroutines-jdk8         | 1.6.4                       | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                                                           | /META-INF/jars/kotlinx-coroutines-jdk8-1.6.4.jar                                    |
\t\t|     9 | kotlinx-datetime-jvm                              | org_jetbrains_kotlinx_kotlinx-datetime-jvm            | 0.4.0                       | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                                                           | /META-INF/jars/kotlinx-datetime-jvm-0.4.0.jar                                       |
\t\t|    27 | kotlinx-serialization-cbor-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm  | 1.5.0                       | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                                                           | /META-INF/jars/kotlinx-serialization-cbor-jvm-1.5.0.jar                             |
\t\t|    16 | kotlinx-serialization-core-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-core-jvm  | 1.5.0                       | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                                                           | /META-INF/jars/kotlinx-serialization-core-jvm-1.5.0.jar                             |
\t\t|    29 | kotlinx-serialization-json-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-json-jvm  | 1.5.0                       | quilted_fabric_loader  | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                                                           | /META-INF/jars/kotlinx-serialization-json-jvm-1.5.0.jar                             |
\t\t|    20 | toml4j                                            | com_moandjiezana_toml_toml4j                          | 0.7.2                       | quilted_fabric_loader  | <mods>\\dynamic-fps-2.2.0.jar                                                                                                                    | /META-INF/jars/toml4j-0.7.2.jar                                                     |
\t\t|    28 | velocity-native                                   | com_velocitypowered_velocity-native                   | 3.1.2-SNAPSHOT              | quilted_fabric_loader  | <mods>\\krypton-0.2.1.jar                                                                                                                        | /META-INF/jars/velocity-native-3.1.2-SNAPSHOT.jar                                   |
\t\t|------:|---------------------------------------------------|-------------------------------------------------------|-----------------------------|------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|
\t\t
\tQuilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
\tLaunched Version: quilt-loader-0.18.10-1.19.4
\tBackend library: LWJGL version 3.3.1 build 7
\tBackend API: Unknown
\tWindow size: <not initialized>
\tGL Caps: Using framebuffer using OpenGL 3.2
\tGL debug messages: <disabled>
\tUsing VBOs: Yes
\tIs Modded: Definitely; Client brand changed to 'quilt'
\tType: Client (map_client.txt)
\tCPU: <unknown>`