export const MissingTitleLog = `---- Crashed! ----
Date/Time: 2023/05/14 08:25:36.8724

-- Crash --

org.quiltmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.server.MinecraftServer failed
\tat org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:529)
\tat org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82)
\tat org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.server.MinecraftServer failed
\tat org.quiltmc.qsl.resource.loader.api.ResourceLoaderEvents.lambda$static$1(ResourceLoaderEvents.java:42)
\tat org.quiltmc.qsl.base.api.event.Event.update(Event.java:374)
\tat org.quiltmc.qsl.base.api.event.Event.<init>(Event.java:247)
\tat org.quiltmc.qsl.base.api.event.Event.create(Event.java:134)
\tat org.quiltmc.qsl.resource.loader.api.ResourceLoaderEvents.<clinit>(ResourceLoaderEvents.java:41)
\tat org.quiltmc.qsl.worldgen.surface_rule.impl.VanillaSurfaceRuleTracker.<init>(VanillaSurfaceRuleTracker.java:54)
\tat org.quiltmc.qsl.worldgen.surface_rule.impl.VanillaSurfaceRuleTracker.<clinit>(VanillaSurfaceRuleTracker.java:37)
\tat net.minecraft.class_6725.handler$epo000$quilt_surface_rule$quilt$injectOverworldRules(class_6725.java:543)
\tat net.minecraft.class_6725.method_39922(class_6725.java:268)
\tat net.minecraft.class_6725.method_39134(class_6725.java:65)
\tat net.minecraft.class_5284.method_30643(class_5284.java:129)
\tat net.minecraft.class_5284.method_31111(class_5284.java:82)
\tat net.minecraft.class_5458.method_44104(class_5458.java:98)
\tat net.minecraft.class_5458.method_30566(class_5458.java:105)
\tat java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
\tat net.minecraft.class_5458.<clinit>(class_5458.java:104)
\tat net.minecraft.class_2378.<clinit>(class_2378.java:326)
\tat net.minecraft.class_2966.method_12851(class_2966.java:50)
\tat net.minecraft.client.main.Main.method_44604(Main.java:161)
\tat net.minecraft.client.main.Main.main(Main.java:51)
\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
\tat java.base/java.lang.reflect.Method.invoke(Method.java:577)
\tat org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527)
\t... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.server.MinecraftServer failed
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:458)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:244)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClassOnly(KnotClassDelegate.java:164)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:150)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:228)
\tat java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
\t... 25 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
\tat org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
\tat org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
\tat org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
\tat org.quiltmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:453)
\t... 30 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector yeetUpdateSuppressionCrash_implOnTickWorlds(Lnet/minecraft/class_3218;Ljava/util/function/BooleanSupplier;)V in #carpet-tis-addition:carpet-tis-addition.mixins.json:rule.yeetUpdateSuppressionCrash.MinecraftServerMixin from mod carpet-tis-addition failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap carpet-tis-addition-mc1.19.2-refmap.json
\tat org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
\tat org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
\tat org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
\tat org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
\tat org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
\tat org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
\tat org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
\tat org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
\t... 33 more


-- Mods --

| Index | Mod                                               | ID                                                   | Version                     | Type    | File Hash (SHA-1)                        | File(s)                                                                                                    | Sub-File                                                                            |
|------:|---------------------------------------------------|------------------------------------------------------|-----------------------------|---------|------------------------------------------|------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|
|   143 | Advancement Plaques                               | advancementplaques                                   | 1.4.6                       | Fabric  | 4af48cf2e71ea3f1ba7987b3bf39662ae3838714 | <mods>\\[è¿›åº¦ç‰ŒåŒ¾] AdvancementPlaques-1.19.2-fabric-1.4.6.jar                                                   |                                                                                     |
|    36 | antlr4-runtime                                    | org_antlr_antlr4-runtime                             | 4.11.1                      | Fabric  |                                          | <mods>\\iris-mc1.19.2-1.6.0.jar                                                                             | /META-INF/jars/antlr4-runtime-4.11.1.jar                                            |
|   104 | AppleSkin                                         | appleskin                                            | 2.4.1+mc1.19                | Fabric  | 7bd52695e82b1ddd1fdb3320154b68bf48dfff37 | <mods>\\[è‹¹æžœçš®] appleskin-fabric-mc1.19-2.4.1.jar                                                             |                                                                                     |
|    34 | atomicfu-jvm                                      | org_jetbrains_kotlinx_atomicfu-jvm                   | 0.20.2                      | Fabric  |                                          | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                      | /META-INF/jars/atomicfu-jvm-0.20.2.jar                                              |
|     0 | Autofish                                          | autofish                                             | 0.9.5-SNAPSHOT              | Fabric  | 223f5c25c2f2984f4d9c94129917a8a3622b1f19 | <mods>\\[è‡ªåŠ¨é’“é±¼] Autofish-0.9.5-fabric-mc1.19.jar                                                             |                                                                                     |
|    54 | BedrockIfy                                        | bedrockify                                           | 1.5.1+mc1.19.1              | Fabric  | ac2803c72ad122b7720158e14ab382fc32588a0d | <mods>\\bedrockify-1.5.1+mc1.19.1.jar                                                                       |                                                                                     |
|   130 | Better Ping Display                               | betterpingdisplay                                    | 1.1.1                       | Fabric  | 7185f04b2089d29af83f4d32366b00c09fb1c90e | <mods>\\[æ›´å¥½çš„å»¶è¿Ÿæ˜¾ç¤º] BetterPingDisplay-Fabric-1.19.2-1.1.1.jar                                                 |                                                                                     |
|    86 | BetterF3                                          | betterf3                                             | 4.0.0                       | Fabric  | 1bbc527d23b53e0aae4d5e1deddf92b1f394b94b | <mods>\\[æ›´å¥½çš„F3] BetterF3-4.0.0-Fabric-1.19.2.jar                                                            |                                                                                     |
|    40 | caffeine                                          | com_github_ben-manes_caffeine_caffeine               | 3.1.2                       | Fabric  |                                          | <mods>\\caxton-0.4.1+1.19.2.jar                                                                             | /META-INF/jars/caffeine-3.1.2.jar                                                   |
|    33 | CaffeineConfig                                    | caffeineconfig                                       | 1.0.0+1.17                  | Fabric  |                                          | <mods>\\[é’  Â· æ‰©å±•] sodium-extra-0.4.16+mc1.19.2-build.90.jar                                                  | /META-INF/jars/mixin-config-1.0.0+1.17.jar                                          |
|    29 | Cardinal Components API (base)                    | cardinal-components-base                             | 5.0.2                       | Fabric  |                                          | <mods>\\PuzzlesLib-v4.4.0-1.19.2-Fabric.jar                                                                 | /META-INF/jars/cardinal-components-base-5.0.2.jar                                   |
|    23 | Cardinal Components API (blocks)                  | cardinal-components-block                            | 5.0.2                       | Fabric  |                                          | <mods>\\PuzzlesLib-v4.4.0-1.19.2-Fabric.jar                                                                 | /META-INF/jars/cardinal-components-block-5.0.2.jar                                  |
|    49 | Cardinal Components API (chunks)                  | cardinal-components-chunk                            | 5.0.2                       | Fabric  |                                          | <mods>\\PuzzlesLib-v4.4.0-1.19.2-Fabric.jar                                                                 | /META-INF/jars/cardinal-components-chunk-5.0.2.jar                                  |
|    24 | Cardinal Components API (entities)                | cardinal-components-entity                           | 5.0.2                       | Fabric  |                                          | <mods>\\PuzzlesLib-v4.4.0-1.19.2-Fabric.jar                                                                 | /META-INF/jars/cardinal-components-entity-5.0.2.jar                                 |
|     5 | Cardinal Components API (worlds)                  | cardinal-components-world                            | 5.0.2                       | Fabric  |                                          | <mods>\\PuzzlesLib-v4.4.0-1.19.2-Fabric.jar                                                                 | /META-INF/jars/cardinal-components-world-5.0.2.jar                                  |
|     6 | Carpet Extra                                      | carpet-extra                                         | 1.4.84                      | Fabric  | cb1394e4dbc5c55f7c9eb6041188905ed72c7933 | <mods>\\[Carpetæ‹“å±•] carpet-extra-1.19.2-1.4.84.jar                                                           |                                                                                     |
|     4 | Carpet Fixes                                      | carpet-fixes                                         | 1.19-1.12.2                 | Fabric  | e351e13c1dd6c5d9b96a10612aa8eba573ecef7c | <mods>\\carpet-fixes-1.19-1.12.2.jar                                                                        |                                                                                     |
|   134 | Carpet Mod                                        | carpet                                               | 1.4.84                      | Fabric  | 9a88c3a004b15b1f776c988d8eae1cc191b4fbee | <mods>\\[Carpet - Fabric ç‰ˆ Carpetï¼ˆæ›´æ—©ç‰ˆæœ¬çš„Carpet Mod åœ¨ä½œè€…çš„ GitHub ä¸»é¡µä¸Šï¼‰] fabric-carpet-1.19.2-1.4.84+v221018.jar |                                                                                     |
|    44 | Carpet TIS Addition                               | carpet-tis-addition                                  | 1.47.0                      | Fabric  | c3ed2c6b358d9c629ae13f8169ffcf39a251ace7 | <mods>\\carpet-tis-addition-mc1.19.2-v1.47.0.jar                                                            |                                                                                     |
|   177 | Caxton                                            | caxton                                               | 0.4.1+1.19.2                | Fabric  | a2dd8eeca661a34264d74a2461d1e52e3c7464fc | <mods>\\caxton-0.4.1+1.19.2.jar                                                                             |                                                                                     |
|   152 | Chat Heads                                        | chat_heads                                           | 0.10.14                     | Fabric  | 932244097bb7e178a3c86fa19f2990898bc3304d | <mods>\\chat_heads-0.10.14-fabric-1.19.2.jar                                                                |                                                                                     |
|    43 | CIT Resewn                                        | citresewn                                            | 1.1.2+1.19.2                | Fabric  | 8eee04b02dcb7543633c8a2001d6bc89abb5d5ac | <mods>\\CITResewn-1.1.2+1.19.2.jar                                                                          |                                                                                     |
|    12 | CIT Resewn: Defaults                              | citresewn-defaults                                   | 1.1.2+1.19.2                | Fabric  |                                          | <mods>\\CITResewn-1.1.2+1.19.2.jar                                                                          | /META-INF/jars/citresewn-defaults-1.1.2+1.19.2.jar                                  |
|    39 | Clickable Advancements Mod                        | clickadv                                             | 3.0                         | Fabric  | e6050645d7800590a2a11faaef9dcffb2ce235a  | <mods>\\[å¯ç‚¹å‡»çš„è¿›åº¦] clickadv-fabric-3.0.jar                                                                    |                                                                                     |
|   175 | Cloth API                                         | cloth-api                                            | 4.0.65                      | Fabric  | be86c751c4e8e54c539abd8530f6d84f97c8188c | <mods>\\cloth-api-4.0.65.jar                                                                                |                                                                                     |
|    61 | Cloth Client Events v0                            | cloth-client-events-v0                               | 4.0.65                      | Fabric  |                                          | <mods>\\cloth-api-4.0.65.jar                                                                                | /META-INF/jars/cloth-client-events-v0-4.0.65.jar                                    |
|   155 | Cloth Common Events v1                            | cloth-common-events-v1                               | 4.0.65                      | Fabric  |                                          | <mods>\\cloth-api-4.0.65.jar                                                                                | /META-INF/jars/cloth-common-events-v1-4.0.65.jar                                    |
|   107 | Cloth Config v8                                   | cloth-config                                         | 8.2.88                      | Fabric  | 4b93c69f22e9bdeeca201992e99632824b55f9cb | <mods>\\cloth-config-8.2.88-fabric.jar                                                                      |                                                                                     |
|    82 | Cloth Scissors API v1                             | cloth-scissors-api-v1                                | 4.0.65                      | Fabric  |                                          | <mods>\\cloth-api-4.0.65.jar                                                                                | /META-INF/jars/cloth-scissors-api-v1-4.0.65.jar                                     |
|    76 | Cloth Utils v1                                    | cloth-utils-v1                                       | 4.0.65                      | Fabric  |                                          | <mods>\\cloth-api-4.0.65.jar                                                                                | /META-INF/jars/cloth-utils-v1-4.0.65.jar                                            |
|    31 | cloth-basic-math                                  | cloth-basic-math                                     | 0.6.1                       | Fabric  |                                          | <mods>\\[è‹¹æžœçš®] appleskin-fabric-mc1.19-2.4.1.jar                                                             | /META-INF/jars/cloth-config-fabric-7.0.65.jar!/META-INF/jars/basic-math-0.6.1.jar   |
|    52 | conditional mixin                                 | conditional-mixin                                    | 0.3.2                       | Fabric  |                                          | <mods>\\carpet-tis-addition-mc1.19.2-v1.47.0.jar                                                            | /META-INF/jars/conditional-mixin-v0.3.2.jar                                         |
|    16 | Continuity                                        | continuity                                           | 2.0.2+1.19                  | Fabric  | b7f4060c66eee13fa1385da89090560de30358e1 | <mods>\\continuity-2.0.2+1.19.jar                                                                           |                                                                                     |
|    48 | core                                              | com_electronwill_night-config_core                   | 3.6.5                       | Fabric  |                                          | <mods>\\ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar                                                        | /META-INF/jars/core-3.6.5.jar                                                       |
|    25 | Distant Horizons                                  | lod                                                  | 1.6.9a                      | Fabric  | a77fb15f91a7b2838c9d402e9e01ed46a3f0cd02 | <mods>\\DistantHorizons-1.6.9a-1.19.2.jar                                                                   |                                                                                     |
|    20 | EasierVillagerTrading                             | easiervillagertrading                                | 1.19.1-fabric0.58.5-1.5.4   | Fabric  | 5df7c30b1ab95250238ac86327c1106a66732de2 | <mods>\\[ç®€å•æ‘æ°‘äº¤æ˜“] easiervillagertrading-1.19.1-fabric0.58.5-1.5.4.jar                                        |                                                                                     |
|    28 | EntityCulling-Fabric                              | entityculling                                        | 1.6.1-mc1.19.2              | Fabric  | 534d7dc7a3f241300e09e7e95d3ae5d4ee5be886 | <mods>\\[å®žä½“æ¸²æŸ“æœºåˆ¶ä¼˜åŒ–] entityculling-fabric-1.6.1-mc1.19.2.jar                                                  |                                                                                     |
|    26 | essential-container                               | essential-container                                  | 1.0.0                       | Fabric  | 5c383c8fd994f6963de85840f2ae75c5b6be9925 | <mods>\\Essential-fabric_1-19-2.jar                                                                         |                                                                                     |
|     8 | essential-loader                                  | essential-loader                                     | 1.0.0                       | Fabric  |                                          | <mods>\\Essential-fabric_1-19-2.jar                                                                         | /essential-loader.jar                                                               |
|    98 | Fabric Language Kotlin                            | fabric-language-kotlin                               | 1.9.4+kotlin.1.8.21         | Fabric  | 98d00c8bb595e7569fadd49290e1a6253d015ed7 | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                      |                                                                                     |
|    55 | FerriteCore                                       | ferritecore                                          | 5.0.3                       | Fabric  | 4a124f8205e39b84a156db2d1e435c5708328d7b | <mods>\\[é“æ°§ä½“ç£èŠ¯] ferritecore-5.0.3-fabric.jar                                                                |                                                                                     |
|    13 | fiber                                             | fiber                                                | 0.23.0-2                    | Fabric  |                                          | <mods>\\[æžç®€è¡€é‡æ˜¾ç¤º] Neat-1.19-32-FABRIC.jar                                                                    | /META-INF/jars/fiber-0.23.0-2.jar                                                   |
|   168 | Forge Config API Port                             | forgeconfigapiport                                   | 4.2.11                      | Fabric  | 00d05a6d57ee557ab216de5527e1434e3cf50c24 | <mods>\\ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar                                                        |                                                                                     |
|    15 | GBfabrictools                                     | gbfabrictools                                        | 1.3.4+1.19                  | Fabric  |                                          | <mods>\\[ç®€å•æ‘æ°‘äº¤æ˜“] easiervillagertrading-1.19.1-fabric0.58.5-1.5.4.jar                                        | /META-INF/jars/GBfabrictools-1.3.4+1.19.jar                                         |
|    50 | glsl-transformer                                  | io_github_douira_glsl-transformer                    | 2.0.0-pre12                 | Fabric  |                                          | <mods>\\iris-mc1.19.2-1.6.0.jar                                                                             | /META-INF/jars/glsl-transformer-2.0.0-pre12.jar                                     |
|   165 | Highlighter                                       | highlighter                                          | 1.1.4                       | Fabric  | 8cd2382c3573602e31810a43209d03dd9bf913d1 | <mods>\\[ç‰©å“é«˜äº®] Highlighter-1.19.1-fabric-1.1.4.jar                                                          |                                                                                     |
|    32 | I18nUpdateMod                                     | i18nupdatemod                                        | 3.4.2                       | Fabric  | d344d84168208bdf8740b3b82b4a8e0df1866d4f | <mods>\\[è‡ªåŠ¨æ±‰åŒ–æ›´æ–°] I18nUpdateMod-3.4.2-all.jar                                                                |                                                                                     |
|   126 | Iceberg                                           | iceberg                                              | 1.0.46                      | Fabric  | cff3a1f0aa7bd3c6f3ac29ae5cb9e6aba991ecd1 | <mods>\\[å†°å±±] Iceberg-1.19.1-fabric-1.0.46.jar                                                               |                                                                                     |
|     2 | Indium                                            | indium                                               | 1.0.9+mc1.19.2              | Fabric  | a74ab16af990cf55dd1a3b5c76eadfc9ca25e25e | <mods>\\[é“Ÿ] indium-1.0.9+mc1.19.2.jar                                                                       |                                                                                     |
|    17 | IngameIME                                         | ingameime                                            | 1.6.6                       | Fabric  | ed0b3f5b69507bbccf8499e4aa91fed0c7ea4fc9 | <mods>\\[æ¸¸æˆå†…è¾“å…¥æ³•] IngameIME-fabric-1.19.2-1.6.6.jar                                                          |                                                                                     |
|    74 | Inventory HUD +                                   | inventoryhud                                         | 3.4.7                       | Fabric  | 522e9d07109e5bceb74b1796757b520bca4a6c4d | <mods>\\[ç‰©å“æ HUD+] invhud.fabric.1.19-3.4.7.jar                                                              |                                                                                     |
|   115 | Inventory Profiles Next                           | inventoryprofilesnext                                | 1.9.7                       | Fabric  | 5a247f678d0ea328674295ba1d5b716be06b153e | <mods>\\InventoryProfilesNext-fabric-1.19-1.9.7.jar                                                         |                                                                                     |
|    79 | Iris                                              | iris                                                 | 1.6.0                       | Fabric  | 2d4343e2e9cbdac41a526f49af43093374229982 | <mods>\\iris-mc1.19.2-1.6.0.jar                                                                             |                                                                                     |
|     1 | Item Scroller                                     | itemscroller                                         | 0.17.1                      | Fabric  | dc49893a040804156c220219cd24befc46a1aac4 | <mods>\\itemscroller-fabric-1.19.2-0.17.1.jar                                                               |                                                                                     |
|   116 | Jade                                              | jade                                                 | 8.7.3                       | Fabric  | 1b3cdd8639ff6083bcf68a76f76a38d1a0afcab7 | <mods>\\Jade-1.19.1-fabric-8.7.3.jar                                                                        |                                                                                     |
|    73 | Java HotSpot(TM) 64-Bit Server VM                 | java                                                 | 18                          | Builtin |                                          | C:\\Program Files\\Java\\jdk-18.0.2                                                                           |                                                                                     |
|    22 | jcpp                                              | org_anarres_jcpp                                     | 1.4.14                      | Fabric  |                                          | <mods>\\iris-mc1.19.2-1.6.0.jar                                                                             | /META-INF/jars/jcpp-1.4.14.jar                                                      |
|    45 | joml                                              | org_joml_joml                                        | 1.10.4                      | Fabric  |                                          | <mods>\\[é’ ] sodium-fabric-mc1.19.2-0.4.4+build.18.jar                                                       | /META-INF/jars/joml-1.10.4.jar                                                      |
|    84 | Just Enough Items                                 | jei                                                  | 11.6.0.1015                 | Fabric  | 3aff3fc5acf4ba5c099e4ff2f60c61932a66e78f | <mods>\\jei-1.19.2-fabric-11.6.0.1015.jar                                                                   |                                                                                     |
|     7 | kotlin-reflect                                    | org_jetbrains_kotlin_kotlin-reflect                  | 1.8.21                      | Fabric  |                                          | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                      | /META-INF/jars/kotlin-reflect-1.8.21.jar                                            |
|    51 | kotlin-stdlib                                     | org_jetbrains_kotlin_kotlin-stdlib                   | 1.8.21                      | Fabric  |                                          | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                      | /META-INF/jars/kotlin-stdlib-1.8.21.jar                                             |
|    42 | kotlin-stdlib-jdk7                                | org_jetbrains_kotlin_kotlin-stdlib-jdk7              | 1.8.21                      | Fabric  |                                          | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                      | /META-INF/jars/kotlin-stdlib-jdk7-1.8.21.jar                                        |
|    35 | kotlin-stdlib-jdk8                                | org_jetbrains_kotlin_kotlin-stdlib-jdk8              | 1.8.21                      | Fabric  |                                          | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                      | /META-INF/jars/kotlin-stdlib-jdk8-1.8.21.jar                                        |
|    47 | kotlinx-coroutines-core-jvm                       | org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm    | 1.6.4                       | Fabric  |                                          | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                      | /META-INF/jars/kotlinx-coroutines-core-jvm-1.6.4.jar                                |
|    41 | kotlinx-coroutines-jdk8                           | org_jetbrains_kotlinx_kotlinx-coroutines-jdk8        | 1.6.4                       | Fabric  |                                          | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                      | /META-INF/jars/kotlinx-coroutines-jdk8-1.6.4.jar                                    |
|    14 | kotlinx-datetime-jvm                              | org_jetbrains_kotlinx_kotlinx-datetime-jvm           | 0.4.0                       | Fabric  |                                          | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                      | /META-INF/jars/kotlinx-datetime-jvm-0.4.0.jar                                       |
|    37 | kotlinx-serialization-cbor-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm | 1.5.0                       | Fabric  |                                          | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                      | /META-INF/jars/kotlinx-serialization-cbor-jvm-1.5.0.jar                             |
|    46 | kotlinx-serialization-core-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-core-jvm | 1.5.0                       | Fabric  |                                          | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                      | /META-INF/jars/kotlinx-serialization-core-jvm-1.5.0.jar                             |
|    38 | kotlinx-serialization-json-jvm                    | org_jetbrains_kotlinx_kotlinx-serialization-json-jvm | 1.5.0                       | Fabric  |                                          | <mods>\\fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar                                                      | /META-INF/jars/kotlinx-serialization-json-jvm-1.5.0.jar                             |
|    58 | Lan Server Properties                             | lanserverproperties                                  | 1.9                         | Fabric  | e49d010832b127e1664f2c222fe8e0f05d854f55 | <mods>\\[è‡ªå®šä¹‰å±€åŸŸç½‘è”æœº] lanserverproperties-1.9-fabric.jar                                                       |                                                                                     |
|    10 | LazyDFU                                           | lazydfu                                              | 0.1.3                       | Fabric  | 0dfa8b03ed408fb7fdada29e01cfebba02af1049 | <mods>\\lazydfu-0.1.3.jar                                                                                   |                                                                                     |
|   101 | libIPN                                            | libipn                                               | 2.0.7                       | Fabric  | 7b69e3d855e6f6a2ed257a16f1db80db3b406efd | <mods>\\libIPN-fabric-1.19-2.0.7.jar                                                                        |                                                                                     |
|     9 | Litematica                                        | litematica                                           | 0.12.7                      | Fabric  | 681469a151edf7ce30209d43d7543db2ae3d4f63 | <mods>\\litematica-fabric-1.19.2-0.12.7.jar                                                                 |                                                                                     |
|   111 | Lithium                                           | lithium                                              | 0.11.1                      | Fabric  | 072a8bad252765e0f21a6f939cf2056fe437228e | <mods>\\lithium-fabric-mc1.19.2-0.11.1.jar                                                                  |                                                                                     |
|    27 | MaLiLib                                           | malilib                                              | 0.13.0                      | Fabric  | adc66c8c481293d6fe316da539eb5b8e46e8ac76 | <mods>\\malilib-fabric-1.19.2-0.13.0.jar                                                                    |                                                                                     |
|    18 | Manningham Mills                                  | mm                                                   | 2.3                         | Fabric  |                                          | <mods>\\caxton-0.4.1+1.19.2.jar                                                                             | /META-INF/jars/Fabric-ASM-v2.3.jar                                                  |
|   180 | Memory Leak Fix                                   | memoryleakfix                                        | 1.0.0                       | Fabric  | 899018ccd70447efe2f198701aeb52bd5eed7c12 | <mods>\\memoryleakfix-fabric-1.17+-1.0.0.jar                                                                |                                                                                     |
|   106 | Minecraft                                         | minecraft                                            | 1.19.2                      | Builtin | 345cae97b7e5decfaba6f2fe47e5a034310fd10  | <game>\\.cache\\quilt_loader\\remappedJars\\minecraft-1.19.2-0.19.0-beta.13\\client-intermediary.jar            |                                                                                     |
|    21 | MiniHUD                                           | minihud                                              | 0.23.3                      | Fabric  | f0e90fdd87301437c9cb7f383da8bac4c030928  | <mods>\\[è¿·ä½ HUD] minihud-fabric-1.19.2-0.23.3.jar                                                            |                                                                                     |
|    66 | MixinExtras                                       | com_github_llamalad7_mixinextras                     | 0.2.0-beta.6                | Fabric  |                                          | <mods>\\memoryleakfix-fabric-1.17+-1.0.0.jar                                                                | /META-INF/jars/mixinextras-fabric-0.2.0-beta.6.jar                                  |
|   136 | Mod Menu                                          | modmenu                                              | 4.2.0-beta.2                | Fabric  | 6e627ee1b31f5be89e14c85e888f47463d8da9c2 | <mods>\\modmenu-4.2.0-beta.2.jar                                                                            |                                                                                     |
|   120 | Nature's Compass                                  | naturescompass                                       | 1.19.2-2.1.0-fabric         | Fabric  | fe1341df482f7ea979972f0e55ef333e59aaa087 | <mods>\\[è‡ªç„¶ç½—ç›˜ï¼ç”Ÿç‰©ç¾¤ç³»æŒ‡å—é’ˆ] NaturesCompass-1.19.2-2.1.0-fabric.jar                                               |                                                                                     |
|    91 | Neat                                              | neat                                                 | 1.19-32-FABRIC              | Fabric  | 3bf85fca996d25070ed073ca27690e02a03ff666 | <mods>\\[æžç®€è¡€é‡æ˜¾ç¤º] Neat-1.19-32-FABRIC.jar                                                                    |                                                                                     |
|   153 | No Chat Reports                                   | nochatreports                                        | 1.19.2-v1.13.12             | Fabric  | 298232cc392f0240191ea62c9cd4d2ff4a99ba97 | <mods>\\[ç¦ç”¨èŠå¤©ä¸¾æŠ¥] NoChatReports-FABRIC-1.19.2-v1.13.12.jar                                                   |                                                                                     |
|   138 | Pick Up Notifier                                  | pickupnotifier                                       | 4.2.4                       | Fabric  | 31b7e036399263a3811a2d13747b88b09f34cd16 | <mods>\\PickUpNotifier-v4.2.4-1.19.2-Fabric.jar                                                             |                                                                                     |
|   103 | Puzzles Lib                                       | puzzleslib                                           | 4.4.0                       | Fabric  | 7c1cb735e94b6f16ff5abd896ccef310a96342e0 | <mods>\\PuzzlesLib-v4.4.0-1.19.2-Fabric.jar                                                                 |                                                                                     |
|   166 | Quilt Advancement API                             | quilt_advancement                                    | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/advancement-3.0.0-beta.29+1.19.2.jar                                 |
|   102 | Quilt Base API                                    | quilt_base                                           | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/qsl_base-3.0.0-beta.29+1.19.2.jar                                    |
|   147 | Quilt Biome API                                   | quilt_biome                                          | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/biome-3.0.0-beta.29+1.19.2.jar                                       |
|   181 | Quilt Block Content Registry API                  | quilt_block_content_registry                         | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/block_content_registry-3.0.0-beta.29+1.19.2.jar                      |
|    77 | Quilt Block Entity API                            | quilt_block_entity                                   | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/block_entity-3.0.0-beta.29+1.19.2.jar                                |
|    90 | Quilt Block Extensions API                        | quilt_block_extensions                               | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/block_extensions-3.0.0-beta.29+1.19.2.jar                            |
|   112 | Quilt Client Command API                          | quilt_client_command                                 | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/client_command-3.0.0-beta.29+1.19.2.jar                              |
|   128 | Quilt Command API                                 | quilt_command                                        | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/command-3.0.0-beta.29+1.19.2.jar                                     |
|   137 | Quilt Crash Info                                  | quilt_crash_info                                     | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/crash_info-3.0.0-beta.29+1.19.2.jar                                  |
|    67 | Quilt DataFixerUpper API                          | quilt_datafixerupper                                 | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/datafixerupper-3.0.0-beta.29+1.19.2.jar                              |
|   145 | Quilt Dimension API                               | quilt_dimension                                      | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/dimension-3.0.0-beta.29+1.19.2.jar                                   |
|   148 | Quilt Entity API                                  | quilt_entity                                         | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/entity-3.0.0-beta.29+1.19.2.jar                                      |
|    97 | Quilt Entity Events                               | quilt_entity_events                                  | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/entity_events-3.0.0-beta.29+1.19.2.jar                               |
|    70 | Quilt Entity Networking API                       | quilt_entity_networking                              | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/entity_networking-3.0.0-beta.29+1.19.2.jar                           |
|    69 | Quilt Entity Rendering API                        | quilt_entity_rendering                               | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/entity_rendering-3.0.0-beta.29+1.19.2.jar                            |
|   170 | Quilt Item Content Registry API                   | quilt_item_content_registry                          | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/item_content_registry-3.0.0-beta.29+1.19.2.jar                       |
|   123 | Quilt Item Extension API                          | quilt_item_extension                                 | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/item_extension-3.0.0-beta.29+1.19.2.jar                              |
|   140 | Quilt Item Group API                              | quilt_item_group                                     | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/item_group-3.0.0-beta.29+1.19.2.jar                                  |
|    81 | Quilt Item Setting API                            | quilt_item_setting                                   | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/item_setting-3.0.0-beta.29+1.19.2.jar                                |
|    56 | Quilt Lifecycle Events                            | quilt_lifecycle_events                               | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/lifecycle_events-3.0.0-beta.29+1.19.2.jar                            |
|   109 | Quilt Loader                                      | quilt_loader                                         | 0.19.0-beta.13              | Quilt   | 8972d6ee197ea345e1aee746200b32837722d86f | I:\\.minecraft\\libraries\\org\\quiltmc\\quilt-loader\\0.19.0-beta.13\\quilt-loader-0.19.0-beta.13.jar            |                                                                                     |
|    62 | Quilt Multipart Entity API                        | quilt_entity_multipart                               | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/multipart-3.0.0-beta.29+1.19.2.jar                                   |
|   139 | Quilt Networking                                  | quilt_networking                                     | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/networking-3.0.0-beta.29+1.19.2.jar                                  |
|   110 | Quilt Points of Interest                          | quilt_points_of_interest                             | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/points_of_interest-3.0.0-beta.29+1.19.2.jar                          |
|    75 | Quilt Recipe API                                  | quilt_recipe                                         | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/recipe-3.0.0-beta.29+1.19.2.jar                                      |
|   150 | Quilt Registry API                                | quilt_registry                                       | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/registry-3.0.0-beta.29+1.19.2.jar                                    |
|   163 | Quilt Registry Entry Attachment                   | quilt_registry_entry_attachment                      | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/registry_entry_attachment-3.0.0-beta.29+1.19.2.jar                   |
|   162 | Quilt Resource Loader                             | quilt_resource_loader                                | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/resource_loader-3.0.0-beta.29+1.19.2.jar                             |
|   156 | Quilt Screen API                                  | quilt_screen                                         | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/screen-3.0.0-beta.29+1.19.2.jar                                      |
|   144 | Quilt Status Effect API                           | quilt_status_effect                                  | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/status_effect-3.0.0-beta.29+1.19.2.jar                               |
|   125 | Quilt Surface Rule API                            | quilt_surface_rule                                   | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/surface_rule-3.0.0-beta.29+1.19.2.jar                                |
|    68 | Quilt Tags API                                    | quilt_tags                                           | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/tags-3.0.0-beta.29+1.19.2.jar                                        |
|   161 | Quilt Tooltip API                                 | quilt_tooltip                                        | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/tooltip-3.0.0-beta.29+1.19.2.jar                                     |
|   172 | Quilt Vehicle API                                 | quilt_vehicle                                        | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/vehicle-3.0.0-beta.29+1.19.2.jar                                     |
|    92 | Quilt Villager API                                | quilt_villager                                       | 3.0.0-beta.29+1.19.2        | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/villager-3.0.0-beta.29+1.19.2.jar                                    |
|   133 | Quilted Fabric API                                | quilted_fabric_api                                   | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   | 25670c34698025b31db03d31913a547b81bd87cd | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           |                                                                                     |
|   117 | Quilted Fabric API Base                           | quilted_fabric_api_base                              | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-api-base-4.0.0-beta.30+0.76.0-1.19.2.jar                      |
|   121 | Quilted Fabric API Lookup API (v1)                | quilted_fabric_api_lookup_api_v1                     | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-api-lookup-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar             |
|   135 | Quilted Fabric Biome API (v1)                     | quilted_fabric_biome_api_v1                          | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-biome-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar                  |
|    57 | Quilted Fabric Block API (v1)                     | quilted_fabric_block_api_v1                          | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-block-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar                  |
|   122 | Quilted Fabric BlockRenderLayer Registration (v1) | quilted_fabric_blockrenderlayer_v1                   | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-blockrenderlayer-v1-4.0.0-beta.30+0.76.0-1.19.2.jar           |
|    71 | Quilted Fabric Client Tags                        | quilted_fabric_client_tags_api_v1                    | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-client-tags-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar            |
|   164 | Quilted Fabric Command API (v1)                   | quilted_fabric_command_api_v1                        | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-command-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar                |
|   108 | Quilted Fabric Command API (v2)                   | quilted_fabric_command_api_v2                        | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-command-api-v2-4.0.0-beta.30+0.76.0-1.19.2.jar                |
|    85 | Quilted Fabric Commands (v0)                      | quilted_fabric_commands_v0                           | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-commands-v0-4.0.0-beta.30+0.76.0-1.19.2.jar                   |
|    53 | Quilted Fabric Containers (v0)                    | quilted_fabric_containers_v0                         | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-containers-v0-4.0.0-beta.30+0.76.0-1.19.2.jar                 |
|   154 | Quilted Fabric Content Registries (v0)            | quilted_fabric_content_registries_v0                 | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-content-registries-v0-4.0.0-beta.30+0.76.0-1.19.2.jar         |
|    60 | Quilted Fabric Convention Tags API (v1)           | quilted_fabric_convention_tags_api_v1                | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-convention-tags-v1-4.0.0-beta.30+0.76.0-1.19.2.jar            |
|    88 | Quilted Fabric Crash Report Info (v1)             | quilted_fabric_crash_report_info_v1                  | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-crash-report-info-v1-4.0.0-beta.30+0.76.0-1.19.2.jar          |
|   178 | Quilted Fabric Data Generation API (v1)           | quilted_fabric_data_generation_api_v1                | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-data-generation-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar        |
|   114 | Quilted Fabric Dimensions API (v1)                | quilted_fabric_dimensions_v1                         | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-dimensions-v1-4.0.0-beta.30+0.76.0-1.19.2.jar                 |
|   129 | Quilted Fabric Entity Events (v1)                 | quilted_fabric_entity_events_v1                      | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-entity-events-v1-4.0.0-beta.30+0.76.0-1.19.2.jar              |
|   169 | Quilted Fabric Events Interaction (v0)            | quilted_fabric_events_interaction_v0                 | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-events-interaction-v0-4.0.0-beta.30+0.76.0-1.19.2.jar         |
|    94 | Quilted Fabric Events Lifecycle (v0)              | quilted_fabric_events_lifecycle_v0                   | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-events-lifecycle-v0-4.0.0-beta.30+0.76.0-1.19.2.jar           |
|   158 | Quilted Fabric Game Rule API (v1)                 | quilted_fabric_game_rule_api_v1                      | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-game-rule-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar              |
|    87 | Quilted Fabric Item API (v1)                      | quilted_fabric_item_api_v1                           | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-item-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar                   |
|    59 | Quilted Fabric Item Groups (v0)                   | quilted_fabric_item_groups_v0                        | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-item-groups-v0-4.0.0-beta.30+0.76.0-1.19.2.jar                |
|   119 | Quilted Fabric Key Binding API (v1)               | quilted_fabric_key_binding_api_v1                    | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-key-binding-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar            |
|    63 | Quilted Fabric Key Bindings (v0)                  | quilted_fabric_keybindings_v0                        | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-keybindings-v0-4.0.0-beta.30+0.76.0-1.19.2.jar                |
|    80 | Quilted Fabric Lifecycle Events (v1)              | quilted_fabric_lifecycle_events_v1                   | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-lifecycle-events-v1-4.0.0-beta.30+0.76.0-1.19.2.jar           |
|   171 | Quilted Fabric Loot API (v2)                      | quilted_fabric_loot_api_v2                           | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-loot-api-v2-4.0.0-beta.30+0.76.0-1.19.2.jar                   |
|    89 | Quilted Fabric Loot Tables (v1)                   | quilted_fabric_loot_tables_v1                        | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-loot-tables-v1-4.0.0-beta.30+0.76.0-1.19.2.jar                |
|   173 | Quilted Fabric Message API (v1)                   | quilted_fabric_message_api_v1                        | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-message-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar                |
|   157 | Quilted Fabric Mining Level API (v1)              | quilted_fabric_mining_level_api_v1                   | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-mining-level-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar           |
|    96 | Quilted Fabric Models (v0)                        | quilted_fabric_models_v0                             | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-models-v0-4.0.0-beta.30+0.76.0-1.19.2.jar                     |
|   179 | Quilted Fabric Networking (v0)                    | quilted_fabric_networking_v0                         | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-networking-v0-4.0.0-beta.30+0.76.0-1.19.2.jar                 |
|    95 | Quilted Fabric Networking API (v1)                | quilted_fabric_networking_api_v1                     | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-networking-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar             |
|   141 | Quilted Fabric Object Builder API (v1)            | quilted_fabric_object_builder_api_v1                 | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-object-builder-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar         |
|   174 | Quilted Fabric Particles (v1)                     | quilted_fabric_particles_v1                          | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-particles-v1-4.0.0-beta.30+0.76.0-1.19.2.jar                  |
|    72 | Quilted Fabric Recipe API (v1)                    | quilted_fabric_recipe_api_v1                         | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-recipe-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar                 |
|   132 | Quilted Fabric Registry Sync (v0)                 | quilted_fabric_registry_sync_v0                      | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-registry-sync-v0-4.0.0-beta.30+0.76.0-1.19.2.jar              |
|    64 | Quilted Fabric Renderer - Indigo                  | quilted_fabric_renderer_indigo                       | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-renderer-indigo-4.0.0-beta.30+0.76.0-1.19.2.jar               |
|   159 | Quilted Fabric Renderer API (v1)                  | quilted_fabric_renderer_api_v1                       | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-renderer-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar               |
|    93 | Quilted Fabric Renderer Registries (v1)           | quilted_fabric_renderer_registries_v1                | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-renderer-registries-v1-4.0.0-beta.30+0.76.0-1.19.2.jar        |
|    78 | Quilted Fabric Rendering (v0)                     | quilted_fabric_rendering_v0                          | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-rendering-v0-4.0.0-beta.30+0.76.0-1.19.2.jar                  |
|   100 | Quilted Fabric Rendering (v1)                     | quilted_fabric_rendering_v1                          | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-rendering-v1-4.0.0-beta.30+0.76.0-1.19.2.jar                  |
|   142 | Quilted Fabric Rendering Data Attachment (v1)     | quilted_fabric_rendering_data_attachment_v1          | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-rendering-data-attachment-v1-4.0.0-beta.30+0.76.0-1.19.2.jar  |
|    99 | Quilted Fabric Rendering Fluids (v1)              | quilted_fabric_rendering_fluids_v1                   | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-rendering-fluids-v1-4.0.0-beta.30+0.76.0-1.19.2.jar           |
|   105 | Quilted Fabric Resource Conditions API (v1)       | quilted_fabric_resource_conditions_api_v1            | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-resource-conditions-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar    |
|   131 | Quilted Fabric Resource Loader (v0)               | quilted_fabric_resource_loader_v0                    | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-resource-loader-v0-4.0.0-beta.30+0.76.0-1.19.2.jar            |
|   151 | Quilted Fabric Screen API (v1)                    | quilted_fabric_screen_api_v1                         | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-screen-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar                 |
|   127 | Quilted Fabric Screen Handler API (v1)            | quilted_fabric_screen_handler_api_v1                 | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-screen-handler-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar         |
|   146 | Quilted Fabric Sound API (v1)                     | quilted_fabric_sound_api_v1                          | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-sound-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar                  |
|   167 | Quilted Fabric Textures (v0)                      | quilted_fabric_textures_v0                           | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-textures-v0-4.0.0-beta.30+0.76.0-1.19.2.jar                   |
|   149 | Quilted Fabric Transfer API (v1)                  | quilted_fabric_transfer_api_v1                       | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-transfer-api-v1-4.0.0-beta.30+0.76.0-1.19.2.jar               |
|   118 | Quilted Fabric Transitive Access Wideners (v1)    | quilted_fabric_transitive_access_wideners_v1         | 4.0.0-beta.30+0.76.0-1.19.2 | Quilt   |                                          | <mods>\\quilt-api-4.0.0-beta.30+0.76.0-1.19.2.jar                                                           | /META-INF/jars/fabric-transitive-access-wideners-v1-4.0.0-beta.30+0.76.0-1.19.2.jar |
|    19 | Reese's Sodium Options                            | reeses-sodium-options                                | 1.4.9+mc1.19.2-build.67     | Fabric  | 3b48ed460ce30c38e6058fdd0c3d6a221913e4e4 | <mods>\\[Reeseçš„é’ è§†é¢‘ç•Œé¢] reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar                                     |                                                                                     |
|    30 | Replay Mod                                        | replaymod                                            | 1.19.1-2.6.10               | Fabric  | e3c8c976218c1138c7a14595a7673e8d461d39b1 | <mods>\\replaymod-1.19.1-2.6.10.jar                                                                         |                                                                                     |
|   160 | Sodium                                            | sodium                                               | 0.4.4+build.18              | Fabric  | 227648dc4f6a8604bafc282612a6de47eff70cd8 | <mods>\\[é’ ] sodium-fabric-mc1.19.2-0.4.4+build.18.jar                                                       |                                                                                     |
|    65 | Sodium Extra                                      | sodium-extra                                         | 0.4.16+mc1.19.2-build.90    | Fabric  | 39a06ef409c407304dd9581b3f2d6537ecd5b63d | <mods>\\[é’  Â· æ‰©å±•] sodium-extra-0.4.16+mc1.19.2-build.90.jar                                                  |                                                                                     |
|   113 | Starlight                                         | starlight                                            | 1.1.1+fabric.ae22326        | Fabric  | de6fe932555604345477db89b59d59249909c640 | <mods>\\[æ˜Ÿå…‰] starlight-1.1.1+fabric.ae22326.jar                                                             |                                                                                     |
|    11 | toml                                              | com_electronwill_night-config_toml                   | 3.6.5                       | Fabric  |                                          | <mods>\\ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar                                                        | /META-INF/jars/toml-3.6.5.jar                                                       |
|     3 | Tweakeroo                                         | tweakeroo                                            | 0.14.3                      | Fabric  | 26f27bfe870778a8986aea9fb403aa812b5f2d83 | <mods>\\tweakeroo-fabric-1.19.2-0.14.3.jar                                                                  |                                                                                     |
|    83 | Xaero's Minimap                                   | xaerominimap                                         | 23.4.1                      | Fabric  | df6818771b6bf6544875d8ae1cb63f4259ee3c81 | <mods>\\Xaeros_Minimap_23.4.1_Fabric_1.19.1.jar                                                             |                                                                                     |
|   176 | Xaero's World Map                                 | xaeroworldmap                                        | 1.30.1                      | Fabric  | 5c071eb196ab9b5fa13e121579a80dfaf16f50aa | <mods>\\XaerosWorldMap_1.30.1_Fabric_1.19.1.jar                                                             |                                                                                     |
|   124 | Xibao                                             | xibaopp                                              | 0.1.0-release-mc1.19        | Fabric  | b7b3c7c1cf10258a58fbca2fa9ca1bc4f852deea | <mods>\\XibaoPlusPlus-Fabric-0.1.0-release-mc1.19.jar                                                       |                                                                                     |
|------:|---------------------------------------------------|------------------------------------------------------|-----------------------------|---------|------------------------------------------|------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------|
Mod Table Version: 2
Plugin Types: {quilted_fabric_loader=[Fabric], quilt_loader=[Quilt, Builtin]}


---- end of report ----`